-- ScholarOS - Version 1 foundation schema
-- Run this entire file once in Supabase Dashboard -> SQL Editor -> New query -> Run.

create extension if not exists pgcrypto;

do $$ begin
  create type public.app_role as enum (
    'student',
    'institute_owner',
    'institute_admin',
    'teacher',
    'reviewer',
    'invigilator',
    'super_admin'
  );
exception when duplicate_object then null;
end $$;

do $$ begin
  create type public.organization_status as enum ('pending', 'active', 'suspended');
exception when duplicate_object then null;
end $$;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  phone text,
  role public.app_role not null default 'student',
  avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.organizations (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null unique,
  school_type text not null,
  city text not null,
  state text not null,
  phone text not null,
  student_count_range text,
  status public.organization_status not null default 'pending',
  created_by uuid not null references public.profiles(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.organization_members (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  member_role public.app_role not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  unique (organization_id, user_id)
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  actor_id uuid references public.profiles(id) on delete set null,
  organization_id uuid references public.organizations(id) on delete set null,
  action text not null,
  entity_type text,
  entity_id text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists organizations_set_updated_at on public.organizations;
create trigger organizations_set_updated_at before update on public.organizations
for each row execute function public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, full_name, role)
  values (new.id, coalesce(new.raw_user_meta_data ->> 'full_name', split_part(new.email, '@', 1)), 'student')
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

create or replace function public.is_super_admin()
returns boolean
language sql
stable
security definer set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'super_admin'
  );
$$;

create or replace function public.is_org_member(p_organization_id uuid)
returns boolean
language sql
stable
security definer set search_path = public
as $$
  select exists (
    select 1 from public.organization_members
    where organization_id = p_organization_id
      and user_id = auth.uid()
      and is_active = true
  );
$$;

create or replace function public.create_school(
  p_name text,
  p_type text,
  p_city text,
  p_state text,
  p_phone text,
  p_student_count text
)
returns uuid
language plpgsql
security definer set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_org uuid;
  v_slug text;
begin
  if v_user is null then
    raise exception 'You must be logged in to create an school.';
  end if;

  if length(trim(p_name)) < 3 then
    raise exception 'School name is too short.';
  end if;

  v_slug := lower(regexp_replace(trim(p_name), '[^a-zA-Z0-9]+', '-', 'g'))
            || '-' || substr(replace(gen_random_uuid()::text, '-', ''), 1, 6);

  insert into public.organizations (
    name, slug, school_type, city, state, phone,
    student_count_range, status, created_by
  ) values (
    trim(p_name), v_slug, trim(p_type), trim(p_city), trim(p_state),
    trim(p_phone), p_student_count, 'pending', v_user
  ) returning id into v_org;

  insert into public.organization_members (organization_id, user_id, member_role)
  values (v_org, v_user, 'institute_owner');

  update public.profiles set role = 'institute_owner' where id = v_user;

  insert into public.audit_logs (actor_id, organization_id, action, entity_type, entity_id)
  values (v_user, v_org, 'organization.created', 'organization', v_org::text);

  return v_org;
end;
$$;

grant execute on function public.create_school(text,text,text,text,text,text) to authenticated;
grant execute on function public.is_super_admin() to anon, authenticated;
grant execute on function public.is_org_member(uuid) to authenticated;

alter table public.profiles enable row level security;
alter table public.organizations enable row level security;
alter table public.organization_members enable row level security;
alter table public.audit_logs enable row level security;

drop policy if exists profiles_select_own_or_admin on public.profiles;
create policy profiles_select_own_or_admin on public.profiles
for select to authenticated
using (id = auth.uid() or public.is_super_admin());

drop policy if exists profiles_update_own_or_admin on public.profiles;
create policy profiles_update_own_or_admin on public.profiles
for update to authenticated
using (id = auth.uid() or public.is_super_admin())
with check (id = auth.uid() or public.is_super_admin());

drop policy if exists organizations_select_members_or_admin on public.organizations;
create policy organizations_select_members_or_admin on public.organizations
for select to authenticated
using (public.is_org_member(id) or public.is_super_admin());

drop policy if exists organizations_update_owner_or_admin on public.organizations;
create policy organizations_update_owner_or_admin on public.organizations
for update to authenticated
using (
  public.is_super_admin() or exists (
    select 1 from public.organization_members m
    where m.organization_id = organizations.id
      and m.user_id = auth.uid()
      and m.member_role in ('institute_owner','institute_admin')
      and m.is_active = true
  )
)
with check (
  public.is_super_admin() or exists (
    select 1 from public.organization_members m
    where m.organization_id = organizations.id
      and m.user_id = auth.uid()
      and m.member_role in ('institute_owner','institute_admin')
      and m.is_active = true
  )
);

drop policy if exists members_select_same_org_or_admin on public.organization_members;
create policy members_select_same_org_or_admin on public.organization_members
for select to authenticated
using (public.is_org_member(organization_id) or public.is_super_admin());

drop policy if exists audit_select_admin_or_org_owner on public.audit_logs;
create policy audit_select_admin_or_org_owner on public.audit_logs
for select to authenticated
using (
  public.is_super_admin() or exists (
    select 1 from public.organization_members m
    where m.organization_id = audit_logs.organization_id
      and m.user_id = auth.uid()
      and m.member_role in ('institute_owner','institute_admin')
      and m.is_active = true
  )
);

-- After registering your own account, run this separately to make yourself super admin:
-- update public.profiles
-- set role = 'super_admin'
-- where id = (select id from auth.users where email = 'YOUR_EMAIL_HERE');
