-- ScholarOS major school subscription and academic-year lifecycle release.
-- Apply after the existing foundation, commerce, question-bank and exam-builder migrations.

create extension if not exists pgcrypto with schema extensions;

do $$ begin create type public.school_subscription_status as enum ('trial','active','expired','suspended','cancelled'); exception when duplicate_object then null; end $$;
do $$ begin create type public.student_membership_status as enum ('active','revoked','completed'); exception when duplicate_object then null; end $$;
do $$ begin create type public.resource_access_label as enum ('free','complimentary','included','paid'); exception when duplicate_object then null; end $$;
do $$ begin create type public.academic_resource_kind as enum ('school_test','previous_year_board','entrance','olympiad','foundation'); exception when duplicate_object then null; end $$;

create table if not exists public.school_subscriptions (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  product_id uuid references public.products(id) on delete set null,
  status public.school_subscription_status not null default 'trial',
  plan_name text not null default 'ScholarOS Annual School Access',
  starts_at date not null,
  ends_at date not null,
  seat_limit integer not null default 250 check (seat_limit > 0),
  resource_access text not null default 'full' check (resource_access in ('full','limited')),
  payment_reference text,
  metadata jsonb not null default '{}'::jsonb,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (organization_id, starts_at, ends_at),
  check (ends_at >= starts_at)
);
create index if not exists school_subscriptions_org_status_idx on public.school_subscriptions(organization_id,status,ends_at desc);

create table if not exists public.student_school_memberships (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  student_id uuid not null references public.profiles(id) on delete cascade,
  academic_year text not null,
  grade integer not null check (grade between 8 and 12),
  section text,
  board text not null,
  tracks text[] not null default '{}',
  status public.student_membership_status not null default 'active',
  promotion_locked boolean not null default false,
  revoked_at timestamptz,
  revoked_by uuid references public.profiles(id) on delete set null,
  promoted_at timestamptz,
  promoted_by uuid references public.profiles(id) on delete set null,
  parent_name text,
  parent_phone text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(organization_id,student_id,academic_year)
);
create index if not exists student_memberships_org_year_idx on public.student_school_memberships(organization_id,academic_year,status,grade);
create index if not exists student_memberships_student_idx on public.student_school_memberships(student_id,status);

create table if not exists public.academic_resources (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  kind public.academic_resource_kind not null,
  access_label public.resource_access_label not null default 'included',
  subscription_required boolean not null default true,
  board text,
  grade_min integer not null default 8 check (grade_min between 8 and 12),
  grade_max integer not null default 12 check (grade_max between 8 and 12 and grade_max >= grade_min),
  required_track text,
  exam_type text,
  subject text,
  source_year integer,
  question_paper_id uuid references public.question_papers(id) on delete set null,
  content_url text,
  is_active boolean not null default true,
  metadata jsonb not null default '{}'::jsonb,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists academic_resources_eligibility_idx on public.academic_resources(kind,board,grade_min,grade_max,required_track,is_active);

create table if not exists public.student_promotion_events (
  id bigint generated by default as identity primary key,
  organization_id uuid not null references public.organizations(id) on delete cascade,
  membership_id uuid references public.student_school_memberships(id) on delete set null,
  student_id uuid not null references public.profiles(id) on delete cascade,
  event_type text not null check (event_type in ('promoted','revoked','completed','bulk_promoted','bulk_revoked')),
  from_academic_year text,
  to_academic_year text,
  from_grade integer,
  to_grade integer,
  actor_id uuid references public.profiles(id) on delete set null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists promotion_events_org_created_idx on public.student_promotion_events(organization_id,created_at desc);

alter table public.question_papers add column if not exists access_label public.resource_access_label not null default 'free';
alter table public.question_papers add column if not exists subscription_required boolean not null default true;
alter table public.question_papers add column if not exists board text;
alter table public.question_papers add column if not exists grade_min integer default 8;
alter table public.question_papers add column if not exists grade_max integer default 12;
alter table public.question_papers add column if not exists required_track text;
alter table public.question_papers add column if not exists source_year integer;
alter table public.question_papers add column if not exists is_previous_year_paper boolean not null default false;

create or replace function public.is_school_manager(p_organization_id uuid)
returns boolean language sql stable security definer set search_path=public as $$
  select public.is_super_admin() or exists(
    select 1 from public.organization_members m where m.organization_id=p_organization_id and m.user_id=auth.uid()
      and m.member_role in ('institute_owner','institute_admin','teacher') and m.is_active=true
  )
$$;
grant execute on function public.is_school_manager(uuid) to authenticated;

create or replace function public.school_subscription_is_active(p_organization_id uuid,p_on_date date default current_date)
returns boolean language sql stable security definer set search_path=public as $$
  select exists(select 1 from public.school_subscriptions s where s.organization_id=p_organization_id and s.status='active' and p_on_date between s.starts_at and s.ends_at)
$$;
grant execute on function public.school_subscription_is_active(uuid,date) to authenticated;

-- Compatibility alias for databases that still expose create_institute from earlier versions.
create or replace function public.create_school(p_name text,p_type text,p_city text,p_state text,p_phone text,p_student_count text)
returns uuid language plpgsql security definer set search_path=public as $$
declare v_org uuid;
begin
  if to_regprocedure('public.create_institute(text,text,text,text,text,text)') is not null then
    execute 'select public.create_institute($1,$2,$3,$4,$5,$6)' into v_org using p_name,p_type,p_city,p_state,p_phone,p_student_count;
    return v_org;
  end if;
  if auth.uid() is null then raise exception 'Login required.'; end if;
  insert into public.organizations(name,slug,institute_type,city,state,phone,student_count_range,status,created_by)
  values(trim(p_name),lower(regexp_replace(trim(p_name),'[^a-zA-Z0-9]+','-','g'))||'-'||substr(replace(gen_random_uuid()::text,'-',''),1,6),trim(p_type),trim(p_city),trim(p_state),trim(p_phone),p_student_count,'pending',auth.uid()) returning id into v_org;
  insert into public.organization_members(organization_id,user_id,member_role) values(v_org,auth.uid(),'institute_owner');
  update public.profiles set role='institute_owner' where id=auth.uid();
  return v_org;
end $$;
grant execute on function public.create_school(text,text,text,text,text,text) to authenticated;

create or replace function public.revoke_school_student(p_membership_id uuid,p_reason text default null)
returns uuid language plpgsql security definer set search_path=public as $$
declare v public.student_school_memberships%rowtype;
begin
  select * into v from public.student_school_memberships where id=p_membership_id for update;
  if v.id is null then raise exception 'Student membership not found.'; end if;
  if not public.is_school_manager(v.organization_id) then raise exception 'School manager permission required.'; end if;
  if v.status<>'active' then return v.id; end if;
  update public.student_school_memberships set status='revoked',promotion_locked=true,revoked_at=now(),revoked_by=auth.uid(),updated_at=now(),metadata=metadata||jsonb_build_object('revoke_reason',p_reason) where id=v.id;
  insert into public.student_promotion_events(organization_id,membership_id,student_id,event_type,from_academic_year,from_grade,to_grade,actor_id,metadata)
  values(v.organization_id,v.id,v.student_id,'revoked',v.academic_year,v.grade,v.grade,auth.uid(),jsonb_build_object('reason',p_reason));
  return v.id;
end $$;
grant execute on function public.revoke_school_student(uuid,text) to authenticated;

create or replace function public.promote_school_student(p_membership_id uuid,p_target_academic_year text)
returns uuid language plpgsql security definer set search_path=public as $$
declare v public.student_school_memberships%rowtype; v_new uuid; v_grade integer; v_status public.student_membership_status;
begin
  select * into v from public.student_school_memberships where id=p_membership_id for update;
  if v.id is null then raise exception 'Student membership not found.'; end if;
  if not public.is_school_manager(v.organization_id) then raise exception 'School manager permission required.'; end if;
  if v.status<>'active' or v.promotion_locked then raise exception 'Revoked or locked students cannot be promoted.'; end if;
  if v.academic_year=p_target_academic_year then return v.id; end if;
  v_grade:=least(12,v.grade+1); v_status:=case when v.grade=12 then 'completed'::public.student_membership_status else 'active'::public.student_membership_status end;
  insert into public.student_school_memberships(organization_id,student_id,academic_year,grade,section,board,tracks,status,promotion_locked,parent_name,parent_phone,promoted_at,promoted_by,metadata)
  values(v.organization_id,v.student_id,p_target_academic_year,v_grade,v.section,v.board,v.tracks,v_status,false,v.parent_name,v.parent_phone,now(),auth.uid(),v.metadata)
  on conflict(organization_id,student_id,academic_year) do update set grade=excluded.grade,section=excluded.section,board=excluded.board,tracks=excluded.tracks,status=excluded.status,promoted_at=now(),promoted_by=auth.uid(),updated_at=now()
  returning id into v_new;
  update public.student_school_memberships set status=case when v.grade=12 then 'completed' else status end,promoted_at=now(),promoted_by=auth.uid(),updated_at=now() where id=v.id;
  insert into public.student_promotion_events(organization_id,membership_id,student_id,event_type,from_academic_year,to_academic_year,from_grade,to_grade,actor_id)
  values(v.organization_id,v.id,v.student_id,case when v.grade=12 then 'completed' else 'promoted' end,v.academic_year,p_target_academic_year,v.grade,v_grade,auth.uid());
  return v_new;
end $$;
grant execute on function public.promote_school_student(uuid,text) to authenticated;

create or replace function public.promote_all_school_students(p_organization_id uuid,p_from_academic_year text,p_target_academic_year text)
returns integer language plpgsql security definer set search_path=public as $$
declare r record; v_count integer:=0;
begin
  if not public.is_school_manager(p_organization_id) then raise exception 'School manager permission required.'; end if;
  for r in select id from public.student_school_memberships where organization_id=p_organization_id and academic_year=p_from_academic_year and status='active' and promotion_locked=false order by id loop
    perform public.promote_school_student(r.id,p_target_academic_year); v_count:=v_count+1;
  end loop;
  return v_count;
end $$;
grant execute on function public.promote_all_school_students(uuid,text,text) to authenticated;

create or replace function public.revoke_all_school_students(p_organization_id uuid,p_academic_year text,p_reason text default null)
returns integer language plpgsql security definer set search_path=public as $$
declare r record; v_count integer:=0;
begin
  if not public.is_school_manager(p_organization_id) then raise exception 'School manager permission required.'; end if;
  for r in select id from public.student_school_memberships where organization_id=p_organization_id and academic_year=p_academic_year and status='active' order by id loop
    perform public.revoke_school_student(r.id,p_reason); v_count:=v_count+1;
  end loop;
  return v_count;
end $$;
grant execute on function public.revoke_all_school_students(uuid,text,text) to authenticated;

create or replace function public.student_can_access_resource(p_resource_id uuid,p_student_id uuid default auth.uid())
returns boolean language sql stable security definer set search_path=public as $$
  select exists(
    select 1 from public.academic_resources r
    join public.student_school_memberships m on m.student_id=p_student_id and m.status='active'
    where r.id=p_resource_id and r.is_active=true
      and m.grade between r.grade_min and r.grade_max
      and (r.board is null or lower(r.board)=lower(m.board))
      and (r.required_track is null or r.required_track=any(m.tracks))
      and (not r.subscription_required or public.school_subscription_is_active(m.organization_id,current_date))
  )
$$;
grant execute on function public.student_can_access_resource(uuid,uuid) to authenticated;

create or replace function public.list_my_eligible_resources()
returns table(id uuid,title text,kind public.academic_resource_kind,access_label public.resource_access_label,subject text,source_year integer,content_url text)
language sql stable security definer set search_path=public as $$
  select r.id,r.title,r.kind,r.access_label,r.subject,r.source_year,r.content_url from public.academic_resources r
  where public.student_can_access_resource(r.id,auth.uid()) order by r.kind,r.source_year desc nulls last,r.title
$$;
grant execute on function public.list_my_eligible_resources() to authenticated;

alter table public.school_subscriptions enable row level security;
alter table public.student_school_memberships enable row level security;
alter table public.academic_resources enable row level security;
alter table public.student_promotion_events enable row level security;

drop policy if exists subscriptions_read on public.school_subscriptions;
create policy subscriptions_read on public.school_subscriptions for select to authenticated using(public.is_super_admin() or public.is_org_member(organization_id));
drop policy if exists subscriptions_admin_write on public.school_subscriptions;
create policy subscriptions_admin_write on public.school_subscriptions for all to authenticated using(public.is_super_admin()) with check(public.is_super_admin());

drop policy if exists memberships_read on public.student_school_memberships;
create policy memberships_read on public.student_school_memberships for select to authenticated using(student_id=auth.uid() or public.is_super_admin() or public.is_org_member(organization_id));
drop policy if exists memberships_school_write on public.student_school_memberships;
create policy memberships_school_write on public.student_school_memberships for all to authenticated using(public.is_school_manager(organization_id)) with check(public.is_school_manager(organization_id));

drop policy if exists resources_metadata_read on public.academic_resources;
create policy resources_metadata_read on public.academic_resources for select to authenticated using(is_active=true or public.is_super_admin());
drop policy if exists resources_admin_write on public.academic_resources;
create policy resources_admin_write on public.academic_resources for all to authenticated using(public.is_super_admin()) with check(public.is_super_admin());

drop policy if exists promotion_events_read on public.student_promotion_events;
create policy promotion_events_read on public.student_promotion_events for select to authenticated using(student_id=auth.uid() or public.is_super_admin() or public.is_org_member(organization_id));

-- New school-created tests default to FREE (no per-test charge); previous-year content should be explicitly marked COMPLIMENTARY.
update public.question_papers set access_label='free',subscription_required=true where is_previous_year_paper=false;
