-- Evidara V6.7: evidence-backed achievements, badges and verifiable certificates.
-- Apply after 16_benchmark_fingerprint_lock_hardening.sql.

create extension if not exists pgcrypto with schema extensions;

create table if not exists public.achievement_definitions (
  code text primary key,
  title text not null,
  description text not null,
  category text not null check (category in ('milestone','performance','growth','consistency','integrity','benchmark')),
  tier text not null check (tier in ('bronze','silver','gold','platinum')),
  icon_key text not null,
  rule_version text not null default '2026.07-v1',
  criteria jsonb not null default '{}'::jsonb,
  certificate_eligible boolean not null default false,
  is_active boolean not null default true,
  display_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.student_achievements (
  id uuid primary key default gen_random_uuid(),
  student_id uuid not null references public.profiles(id) on delete cascade,
  organization_id uuid not null references public.organizations(id) on delete cascade,
  definition_code text not null references public.achievement_definitions(code) on delete restrict,
  rule_version text not null,
  source_type text not null check (source_type in ('exam_attempt','benchmark_contribution','aggregate_refresh','backfill')),
  source_id uuid,
  evidence jsonb not null default '{}'::jsonb,
  status text not null default 'active' check (status in ('active','revoked')),
  awarded_at timestamptz not null default now(),
  last_evaluated_at timestamptz not null default now(),
  revoked_at timestamptz,
  revoked_by uuid references public.profiles(id) on delete set null,
  revoked_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(student_id, organization_id, definition_code)
);

create table if not exists public.achievement_certificates (
  id uuid primary key default gen_random_uuid(),
  achievement_id uuid not null references public.student_achievements(id) on delete restrict,
  student_id uuid not null references public.profiles(id) on delete restrict,
  organization_id uuid not null references public.organizations(id) on delete restrict,
  certificate_number text not null unique,
  verification_code text not null unique,
  student_name_snapshot text not null,
  organization_name_snapshot text not null,
  achievement_title_snapshot text not null,
  achievement_description_snapshot text not null,
  rule_version text not null,
  evidence_summary text not null,
  status text not null default 'active' check (status in ('active','revoked')),
  visibility text not null default 'link_only' check (visibility in ('link_only')),
  issued_at timestamptz not null default now(),
  issued_by uuid references public.profiles(id) on delete set null,
  revoked_at timestamptz,
  revoked_by uuid references public.profiles(id) on delete set null,
  revoked_reason text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists achievement_certificates_active_achievement_idx
  on public.achievement_certificates(achievement_id)
  where status = 'active';

create table if not exists public.achievement_audit_events (
  id bigint generated by default as identity primary key,
  achievement_id uuid references public.student_achievements(id) on delete cascade,
  certificate_id uuid references public.achievement_certificates(id) on delete cascade,
  student_id uuid references public.profiles(id) on delete set null,
  organization_id uuid references public.organizations(id) on delete set null,
  actor_id uuid references public.profiles(id) on delete set null,
  event_type text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists student_achievements_student_idx
  on public.student_achievements(student_id, status, awarded_at desc);
create index if not exists student_achievements_org_idx
  on public.student_achievements(organization_id, status, awarded_at desc);
create index if not exists achievement_certificates_student_idx
  on public.achievement_certificates(student_id, status, issued_at desc);
create index if not exists achievement_certificates_org_idx
  on public.achievement_certificates(organization_id, status, issued_at desc);
create index if not exists achievement_audit_events_org_idx
  on public.achievement_audit_events(organization_id, created_at desc);

insert into public.achievement_definitions(
  code,title,description,category,tier,icon_key,rule_version,criteria,certificate_eligible,display_order
) values
  ('first_assessment','First Evidence','Completed the first verified Evidara assessment.','milestone','bronze','flag','2026.07-v1',
   '{"submitted_attempts_minimum":1,"responsible_use":"A completion milestone, not a measure of ability."}'::jsonb,false,10),
  ('assessment_excellence','Assessment Excellence','Scored at least 90% on a verified assessment with meaningful question coverage.','performance','silver','star','2026.07-v1',
   '{"percentage_minimum":90,"questions_minimum":10,"responsible_use":"Applies only to the cited paper and scoring context."}'::jsonb,true,20),
  ('perfect_score','Perfect Score','Achieved 100% on a verified assessment.','performance','gold','trophy','2026.07-v1',
   '{"percentage_minimum":100,"questions_minimum":5,"responsible_use":"Recognises one exact assessment result; it is not a prediction."}'::jsonb,true,30),
  ('growth_milestone','Growth Milestone','Improved by at least 15 percentage points between comparable assessments of the same exam type.','growth','silver','trending-up','2026.07-v1',
   '{"percentage_point_improvement_minimum":15,"comparison":"same_exam_type","responsible_use":"Shows observed improvement between two assessments, not permanent growth."}'::jsonb,true,40),
  ('consistent_performer','Consistent Performer','Maintained at least 75% across the three most recent verified assessments.','consistency','gold','layers','2026.07-v1',
   '{"recent_attempts":3,"percentage_minimum_each":75,"responsible_use":"Uses only the current three-assessment evidence window."}'::jsonb,true,50),
  ('integrity_streak','Integrity Streak','Completed five recent verified assessments without a recorded integrity event.','integrity','gold','shield','2026.07-v1',
   '{"recent_attempts":5,"maximum_integrity_events_each":0,"responsible_use":"Reflects recorded platform events only and is not a character judgement."}'::jsonb,true,60),
  ('benchmark_participant','Shared Benchmark Participant','Completed a valid shared-paper benchmark contribution.','benchmark','bronze','network','2026.07-v1',
   '{"valid_benchmark_contributions_minimum":1,"responsible_use":"Recognises participation; no school or student ranking is implied."}'::jsonb,false,70),
  ('benchmark_top_decile','Benchmark Distinction','Placed in the top external decile after the privacy minimum was reached.','benchmark','platinum','medal','2026.07-v1',
   '{"external_percentile_minimum":90,"privacy_threshold_required":true,"responsible_use":"The percentile is specific to the exact paper and anonymous comparison pool."}'::jsonb,true,80)
on conflict(code) do update set
  title=excluded.title,
  description=excluded.description,
  category=excluded.category,
  tier=excluded.tier,
  icon_key=excluded.icon_key,
  rule_version=excluded.rule_version,
  criteria=excluded.criteria,
  certificate_eligible=excluded.certificate_eligible,
  display_order=excluded.display_order,
  updated_at=now();

alter table public.achievement_definitions enable row level security;
alter table public.student_achievements enable row level security;
alter table public.achievement_certificates enable row level security;
alter table public.achievement_audit_events enable row level security;

-- Browser clients use authenticated server APIs. Raw award evidence and certificate
-- audit records are not directly queryable from anon or authenticated clients.
revoke all on public.achievement_definitions from anon, authenticated;
revoke all on public.student_achievements from anon, authenticated;
revoke all on public.achievement_certificates from anon, authenticated;
revoke all on public.achievement_audit_events from anon, authenticated;

comment on table public.student_achievements is
  'One versioned, evidence-backed achievement per learner, school and transparent rule.';
comment on table public.achievement_certificates is
  'Link-only verifiable certificate snapshots. Verification reveals limited award information to the code holder.';
comment on column public.student_achievements.evidence is
  'Exact observed values and source identifiers used when the rule was evaluated.';
