"use client";
import Link from "next/link";
import { useEffect,useState } from "react";
import { CheckCircle2,CircleAlert,CircleDashed } from "lucide-react";
import { isSupabaseConfigured,supabase } from "@/lib/supabase";
import { Navbar } from "@/components/Navbar";
import { legalDetailsConfigured } from "@/config/site";

type State="waiting"|"ok"|"error";
export default function SetupCheck(){
 const [commerce,setCommerce]=useState<State>("waiting");const [questionBank,setQuestionBank]=useState<State>("waiting");const [paperBuilder,setPaperBuilder]=useState<State>("waiting");const [username,setUsername]=useState<State>("waiting");const [messages,setMessages]=useState<Record<string,string>>({});
 useEffect(()=>{async function check(){if(!supabase){setCommerce("error");setQuestionBank("error");setPaperBuilder("error");setUsername("error");setMessages({all:"Supabase environment keys are not present. Demo Mode remains available."});return;}
  const [store,subjects,papers,userCheck]=await Promise.all([supabase.rpc("get_store_products"),supabase.from("subjects").select("id",{count:"exact",head:true}),supabase.from("question_papers").select("id",{count:"exact",head:true}),supabase.rpc("is_username_available",{p_username:`setup_test_${Date.now()}`})]);
  setCommerce(store.error?"error":"ok");setQuestionBank(subjects.error?"error":"ok");setPaperBuilder(papers.error?"error":"ok");setUsername(userCheck.error?"error":"ok");setMessages({commerce:store.error?.message||"Products and commerce are reachable.",questions:subjects.error?.message||"Question-bank tables are reachable.",papers:papers.error?.message||"Version 4 paper-builder tables are reachable.",username:userCheck.error?.message||"Unique username validation is reachable."});}
 void check()},[]);
 const rows=[{n:"Static Next.js build",s:"ok" as State,d:"The project exports to Hostinger with all Version 4 routes."},{n:"Supabase environment keys",s:isSupabaseConfigured?"ok" as State:"error" as State,d:isSupabaseConfigured?"Project URL and publishable key detected.":"Add NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY."},{n:"Version 2 commerce",s:commerce,d:messages.commerce||messages.all||"Checking…"},{n:"Version 3 question bank",s:questionBank,d:messages.questions||messages.all||"Checking…"},{n:"Version 4 paper builder",s:paperBuilder,d:messages.papers||messages.all||"Checking…"},{n:"Username registration RPC",s:username,d:messages.username||messages.all||"Checking…"},{n:"Google OAuth",s:isSupabaseConfigured?"waiting" as State:"error" as State,d:"Complete a real Google login in an Incognito window."},{n:"Email confirmation disabled",s:"waiting" as State,d:"Confirm Authentication → Providers → Email → Confirm email is OFF."},{n:"Legal and contact details",s:legalDetailsConfigured?"ok" as State:"error" as State,d:legalDetailsConfigured?"Business details have been configured.":"Replace placeholders in src/config/site.ts before real payments."},{n:"Razorpay Edge Functions",s:isSupabaseConfigured?"waiting" as State:"error" as State,d:"Complete one Test Mode payment and confirm an entitlement."},{n:"Question image storage",s:questionBank==="ok"?"waiting" as State:"error" as State,d:"Upload one image from the question editor and confirm its public preview."}];
 return <><Navbar/><main className="rm-container" style={{padding:"42px 0"}}><span className="rm-label">Live setup assistant</span><h1 style={{fontSize:38,color:"#131e35",margin:"6px 0"}}>Version 4 system check</h1><p style={{color:"#667085"}}>Green confirms an automatic database test. Yellow items require a real browser test because they depend on external account settings.</p><div className="rm-card" style={{padding:20,marginTop:22}}>{rows.map(r=><div key={r.n} className="check-row" style={{display:"grid",gridTemplateColumns:"32px 240px 1fr",gap:12,alignItems:"center",padding:"15px 4px",borderBottom:"1px solid #eef1f5"}}>{r.s==="ok"?<CheckCircle2 color="#137a3a"/>:r.s==="error"?<CircleAlert color="#b42318"/>:<CircleDashed color="#b77d00"/>}<strong>{r.n}</strong><span style={{color:"#667085"}}>{r.d}</span></div>)}</div><div style={{display:"flex",gap:12,flexWrap:"wrap",marginTop:18}}><Link href="/admin/papers/" className="rm-btn-primary">Open Paper Builder</Link><Link href="/admin/questions/" className="rm-btn-secondary">Open Question Bank</Link><Link href="/admin/questions/import/" className="rm-btn-secondary">Test Bulk Import</Link><Link href="/login/" className="rm-btn-secondary">Test Registration</Link></div><style jsx>{`@media(max-width:650px){.check-row{grid-template-columns:30px 1fr!important}.check-row span{grid-column:2}}`}</style></main></>
}
