function renderSuper(){
  if(state.page==='schools') return schoolsPage();
  if(state.page==='assessments') return assessmentsPage();
  if(state.page==='intelligence') return intelligencePage();
  if(state.page==='consent') return consentPage();
  if(state.page==='roadmap') return roadmapPage();
  return `<div class="page-head"><div><h3>Command centre</h3><p>See adoption, assessment quality, student potential and permissioned opportunities across every school.</p></div><button class="btn btn-primary" data-modal="school">＋ Onboard school</button></div>
  <div class="grid grid-4">${metric('▦','4','Schools in pipeline','2 active')}${metric('♙','1,671','Students mapped','+14.8%')}${metric('✓','3,942','Tests completed','+22.4%')}${metric('◎','184','Counselling opt-ins','11.0%','warn')}</div>
  <div class="grid grid-3" style="margin-top:18px">
    <div class="card span-2"><div class="card-head"><div><h4 class="card-title">Assessment participation</h4><p class="card-sub">Weekly completed attempts across partner schools</p></div>${badge('Live')}</div><div class="chart-bars">${[32,48,43,67,54,81,72,96,110,124,118,145].map((v,i)=>`<div class="bar-col"><div class="bar ${i>8?'gold':''}" style="height:${v}px"></div><div class="bar-label">W${i+1}</div></div>`).join('')}</div></div>
    <div class="card card-pad"><h4 class="card-title">Data readiness</h4><p class="card-sub">Can the platform produce trustworthy benchmarks?</p><div class="donut-wrap" style="margin:18px 0"><div class="donut"></div><div class="donut-label"><strong>88%</strong><span>ready</span></div></div><div class="list"><div><div class="metric-label">Consent completeness</div>${pct(86)}</div><div><div class="metric-label">Question calibration</div>${pct(79)}</div><div><div class="metric-label">Repeat-test coverage</div>${pct(72)}</div></div></div>
  </div>
  <div class="grid grid-2" style="margin-top:18px">
    <div class="card"><div class="card-head"><div><h4 class="card-title">Schools requiring attention</h4><p class="card-sub">Operational blockers before the next assessment</p></div></div><div class="list card-pad"><div class="list-item"><div class="rank">1</div><div class="list-item-main"><h4>Horizon Public School</h4><p>76% parent consent; 43 students pending</p></div>${badge('At risk')}</div><div class="list-item"><div class="rank">2</div><div class="list-item-main"><h4>Excel English School</h4><p>Proposal shared; pilot date not confirmed</p></div>${badge('Proposal')}</div><div class="list-item"><div class="rank">3</div><div class="list-item-main"><h4>Green Valley School</h4><p>Grade 10 parent webinar due this week</p></div>${badge('Scheduled')}</div></div></div>
    <div class="card"><div class="card-head"><div><h4 class="card-title">Opportunity segments</h4><p class="card-sub">Academic potential and enrolment intent kept separate</p></div></div><div class="table-wrap"><table class="table"><thead><tr><th>Segment</th><th>Students</th><th>Next action</th></tr></thead><tbody><tr><td>Academic Elite</td><td>84</td><td>Advanced cohort</td></tr><tr><td>High potential, careless</td><td>132</td><td>Accuracy clinic</td></tr><tr><td>Grade 11 counselling opt-in</td><td>91</td><td>Parent meeting</td></tr><tr><td>Long-term NEET prospects</td><td>38</td><td>Mentor review</td></tr></tbody></table></div></div>
  </div>`;
}

function schoolsPage(){return `<div class="page-head"><div><h3>Partner schools</h3><p>Each school remains a separate tenant with its own students, staff, reports and branding.</p></div><button class="btn btn-primary" data-modal="school">＋ Add school</button></div><div class="toolbar"><input class="input" style="max-width:320px" placeholder="Search school, city or coordinator"><select class="select" style="max-width:180px"><option>All statuses</option><option>Active</option><option>Pilot</option><option>Proposal</option></select></div><div class="card table-wrap"><table class="table"><thead><tr><th>School</th><th>City</th><th>Grades</th><th>Students</th><th>Consent</th><th>Status</th><th></th></tr></thead><tbody>${state.schools.map(s=>`<tr><td><strong>${s.name}</strong></td><td>${s.city}</td><td>${s.grades}</td><td>${s.students}</td><td>${s.consent?`${s.consent}%`:'—'}</td><td>${badge(s.status)}</td><td><button class="btn btn-outline btn-sm">Open</button></td></tr>`).join('')}</tbody></table></div>`}
function assessmentsPage(){return `<div class="page-head"><div><h3>Assessment studio</h3><p>Create board-aligned, foundation, Olympiad or NEET tests from calibrated question blueprints.</p></div><button class="btn btn-primary" data-modal="assessment">＋ Create assessment</button></div><div class="grid grid-4">${metric('✓','18','Active assessments','6 this month')}${metric('▤','12,640','Questions','68% calibrated')}${metric('◷','54 min','Average duration','-4 min')}${metric('◎','0.41','Avg discrimination','Good')}</div><div class="card" style="margin-top:18px"><div class="card-head"><div><h4 class="card-title">Upcoming and active</h4><p class="card-sub">Delivery readiness, participation and report release</p></div></div><div class="table-wrap"><table class="table"><thead><tr><th>Assessment</th><th>Audience</th><th>Mode</th><th>Questions</th><th>Attempts</th><th>Status</th></tr></thead><tbody><tr><td><strong>Grade 10 Science Pathway Benchmark</strong></td><td>4 schools</td><td>CBT + OMR</td><td>80</td><td>622</td><td>${badge('Live')}</td></tr><tr><td><strong>Grade 9 Foundation Challenge 02</strong></td><td>2 schools</td><td>CBT</td><td>60</td><td>288</td><td>${badge('Scheduled')}</td></tr><tr><td><strong>NEET Full Syllabus Mock 04</strong></td><td>Grade 12</td><td>CBT</td><td>180</td><td>164</td><td>${badge('Completed')}</td></tr></tbody></table></div></div>`}
function intelligencePage(){return `<div class="page-head"><div><h3>Student intelligence</h3><p>Separate learning potential from marketing intent, then prescribe the correct academic action.</p></div><button class="btn btn-outline">Export permissioned leads</button></div><div class="notice blue">Academic scores must never be treated as consent to market. Only parent-verified counselling opt-ins appear in the opportunity pipeline.</div><div class="grid grid-3" style="margin-top:18px"><div class="card card-pad"><h4 class="card-title">Academic Elite</h4><div class="metric-value">84</div><p class="card-sub">Top 5%, consistent speed and accuracy</p>${pct(92)}</div><div class="card card-pad"><h4 class="card-title">High Potential, Careless</h4><div class="metric-value">132</div><p class="card-sub">Strong hard-question success; easy marks lost</p>${pct(74)}</div><div class="card card-pad"><h4 class="card-title">Fast Improvers</h4><div class="metric-value">96</div><p class="card-sub">More than 12 percentile gain across 3 tests</p>${pct(81)}</div></div><div class="card" style="margin-top:18px"><div class="card-head"><div><h4 class="card-title">Permissioned opportunity pipeline</h4><p class="card-sub">Only families who explicitly requested counselling</p></div></div><div class="table-wrap"><table class="table"><thead><tr><th>Student</th><th>Grade</th><th>Academic segment</th><th>Interest</th><th>Engagement</th><th>Action</th></tr></thead><tbody><tr><td>Ananya R.</td><td>10</td><td>${badge('Academic Elite')}</td><td>NEET</td><td>High</td><td><button class="btn btn-primary btn-sm">Book parent call</button></td></tr><tr><td>Rohan S.</td><td>10</td><td>${badge('Fast Improver')}</td><td>Undecided</td><td>High</td><td><button class="btn btn-outline btn-sm">Send pathway report</button></td></tr><tr><td>Meghana K.</td><td>12</td><td>${badge('Long-term prospect')}</td><td>NEET repeat</td><td>Medium</td><td><button class="btn btn-outline btn-sm">Mentor review</button></td></tr></tbody></table></div></div>`}
function consentPage(){return `<div class="page-head"><div><h3>Consent and privacy</h3><p>Purpose-specific controls for minor students, parents, schools and programme communication.</p></div><button class="btn btn-primary">Create consent campaign</button></div><div class="grid grid-4">${metric('⚿','1,436','Assessment consent','86%')}${metric('✉','1,108','Academic updates','66%')}${metric('☎','184','Counselling opt-in','11%')}${metric('⌫','7','Deletion requests','All resolved')}</div><div class="grid grid-2" style="margin-top:18px"><div class="card card-pad"><h4 class="card-title">Three-layer permission model</h4><div class="action-plan"><div class="action-step"><div><strong>Assessment participation</strong><span>Required to take the test and receive the academic report.</span></div></div><div class="action-step"><div><strong>Academic communication</strong><span>Optional reminders, practice resources and future assessments.</span></div></div><div class="action-step"><div><strong>Programme counselling</strong><span>Separate, unchecked-by-default consent for Grade 11, NEET or JEE guidance.</span></div></div></div></div><div class="card card-pad"><h4 class="card-title">Operational controls</h4><div class="list" style="margin-top:14px"><div class="list-item"><div class="rank">✓</div><div class="list-item-main"><h4>Parent OTP verification</h4><p>Consent identity and timestamp recorded</p></div></div><div class="list-item"><div class="rank">↺</div><div class="list-item-main"><h4>Consent withdrawal</h4><p>Marketing workflows stop immediately</p></div></div><div class="list-item"><div class="rank">⌫</div><div class="list-item-main"><h4>Retention and deletion</h4><p>School and platform responsibilities tracked</p></div></div></div></div></div>`}
function roadmapPage(){return `<div class="page-head"><div><h3>Production roadmap</h3><p>Build version after version without losing the assessment intelligence core.</p></div>${badge('Version 1 live')}</div><div class="grid grid-2"><div class="card card-pad"><h4 class="card-title">V1 — Functional pilot</h4><p class="card-sub">Current release</p><div class="action-plan"><div class="action-step"><div><strong>Multi-role product shell</strong><span>Super admin, organisation admin, school admin and student views.</span></div></div><div class="action-step"><div><strong>Assessment and analytics journey</strong><span>Demo test, error diagnosis, mastery heatmap and action plan.</span></div></div><div class="action-step"><div><strong>School, consent and opportunity modules</strong><span>Commercial workflow represented end-to-end.</span></div></div></div></div><div class="card card-pad"><h4 class="card-title">V2 — Connected data</h4><p class="card-sub">Next engineering release</p><div class="action-plan"><div class="action-step"><div><strong>Supabase authentication and tenancy</strong><span>Secure role permissions and school data isolation.</span></div></div><div class="action-step"><div><strong>Question bank and test engine</strong><span>CRUD, imports, LaTeX, images, timers and autosave.</span></div></div><div class="action-step"><div><strong>Real analytics pipeline</strong><span>Attempt events, percentile cohorts, psychometrics and reports.</span></div></div></div></div><div class="card card-pad"><h4 class="card-title">V3 — School operations</h4><div class="action-plan"><div class="action-step"><div><strong>OMR generation and scan import</strong><span>Offline school examinations connected to the same analytics.</span></div></div><div class="action-step"><div><strong>Parent portal and report access</strong><span>OTP report release, bilingual reports and counselling booking.</span></div></div><div class="action-step"><div><strong>Odoo integration</strong><span>Push only permissioned leads with campaign attribution.</span></div></div></div></div><div class="card card-pad"><h4 class="card-title">V4 — Differentiation</h4><div class="action-plan"><div class="action-step"><div><strong>Adaptive practice</strong><span>Daily tasks based on misconception and forgetting patterns.</span></div></div><div class="action-step"><div><strong>Teacher intervention engine</strong><span>Auto-created small groups and ready-to-use lesson actions.</span></div></div><div class="action-step"><div><strong>Benchmark marketplace</strong><span>District, state and national challenges with verified recognition.</span></div></div></div></div></div>`}

