import { requirePhase1PublicFeature } from '@/lib/phase1PublicGate';
import type { Metadata } from 'next';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { PublicSeoShell } from '@/components/seo/PublicSeoShell';
import { publicRpc, SITE_URL } from '@/lib/seo-public';
import { JsonLd } from '@/components/seo/JsonLd';

export const dynamic='force-dynamic';
type P={id:string;slug:string;title:string;description?:string;exam_type?:string;source_year?:number;test_type?:string;duration_minutes?:number;total_questions?:number;total_marks?:number;seo_title?:string;seo_description?:string};
async function get(slug:string){const p=await publicRpc<P>('get_public_paper_v15',{p_slug:slug});return p&&p.id?p:null}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const{slug}=await params;const p=await get(slug);if(!p)return{title:'Question Paper | Evidara',robots:{index:false,follow:false}};return{title:p.seo_title||p.title,description:p.seo_description||p.description,alternates:{canonical:`${SITE_URL}/question-papers/${p.slug}/`}}}
export default async function Page({params}:{params:Promise<{slug:string}>}){requirePhase1PublicFeature('publicQuestionPapers');const{slug}=await params;const p=await get(slug);if(!p)notFound();return <PublicSeoShell><JsonLd data={{'@context':'https://schema.org','@type':'LearningResource',name:p.title,about:p.exam_type,educationalUse:'practice',dateCreated:p.source_year?`${p.source_year}-01-01`:undefined}}/><article className="mx-auto max-w-4xl px-5 py-12"><p className="font-bold uppercase tracking-[.16em] text-[#0E7774]">{p.exam_type||'Exam'} {p.source_year||'Model Paper'}</p><h1 className="mt-3 text-4xl font-extrabold">{p.title}</h1><p className="mt-4 text-lg leading-8 text-[#65757C]">{p.description||p.seo_description||'Practise this question paper online with Evidara.'}</p><div className="mt-7 grid gap-4 sm:grid-cols-3">{p.total_questions?<div className="rounded-xl bg-white p-5"><div className="text-sm text-[#65757C]">Questions</div><div className="mt-1 text-2xl font-bold">{p.total_questions}</div></div>:null}{p.duration_minutes?<div className="rounded-xl bg-white p-5"><div className="text-sm text-[#65757C]">Duration</div><div className="mt-1 text-2xl font-bold">{p.duration_minutes} min</div></div>:null}{p.total_marks?<div className="rounded-xl bg-white p-5"><div className="text-sm text-[#65757C]">Marks</div><div className="mt-1 text-2xl font-bold">{p.total_marks}</div></div>:null}</div><section className="mt-8 rounded-2xl bg-[#142F35] p-7 text-white"><h2 className="text-2xl font-bold">Practise this paper with analytics</h2><p className="mt-2 text-[#D4E2E0]">Sign in to Evidara to take available papers online, save your result and analyse strengths and weaknesses.</p><Link href="/products/" className="mt-5 inline-block rounded-lg bg-white px-4 py-2 font-bold text-[#142F35]">Explore practice options</Link></section></article></PublicSeoShell>}
