'use client';

import { useEffect, useMemo, useState } from 'react';
import { ChevronLeft, Download, FileText, Folder, FolderPlus, LoaderCircle, RefreshCw, Search, Trash2, Upload } from 'lucide-react';
import { supabase } from '@/lib/supabase';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';

type FolderRow={id:string;resource_scope:string;organization_id:string|null;parent_id:string|null;name:string;class_level:string|null;subject:string|null;chapter:string|null};
type ResourceRow={id:string;title:string;resource_scope:string;organization_id:string|null;folder_id:string|null;content_url:string|null;file_name:string|null;mime_type:string|null;size_bytes:number|null;subject:string|null;grade_min:number;grade_max:number;metadata?:Record<string,unknown>|null};
type Payload={role:string;mode:string;organizationId:string|null;canManage:boolean;folders:FolderRow[];resources:ResourceRow[]};

function fmtBytes(v:number){if(v>=1024**3)return `${(v/1024**3).toFixed(2)} GB`;if(v>=1024**2)return `${(v/1024**2).toFixed(1)} MB`;if(v>=1024)return `${(v/1024).toFixed(1)} KB`;return `${v||0} B`}
async function token(){if(!supabase)throw new Error('Supabase is not configured.');const {data,error}=await supabase.auth.getSession();if(error||!data.session?.access_token)throw new Error(error?.message||'Sign in again.');return data.session.access_token;}

export function ResourceManagerV14({mode}:{mode:'school'|'student'|'platform'}){
  const [data,setData]=useState<Payload|null>(null);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('');const [folderId,setFolderId]=useState<string|null>(null);const [query,setQuery]=useState('');
  const [folderOpen,setFolderOpen]=useState(false);const [folderDraft,setFolderDraft]=useState({name:'',classLevel:'',subject:'',chapter:''});const [uploadOpen,setUploadOpen]=useState(false);const [file,setFile]=useState<File|null>(null);const [draft,setDraft]=useState({title:'',subject:'General',gradeMin:'1',gradeMax:'12',description:''});
  async function load(){setLoading(true);setError('');try{const t=await token();const r=await fetch(`/api/resources-v14/?mode=${mode}`,{headers:{Authorization:`Bearer ${t}`},cache:'no-store'});const p=await r.json();if(!r.ok)throw new Error(p.error||'Unable to load resources.');setData(p);}catch(e){setError(e instanceof Error?e.message:'Unable to load resources.');setData(null);}finally{setLoading(false)}}
  useEffect(()=>{void load()},[mode]);
  const currentFolder=data?.folders.find(f=>f.id===folderId)||null;const canManageHere=Boolean(data?.canManage && (mode==='platform' || !currentFolder || currentFolder.resource_scope==='organization'));const childFolders=(data?.folders||[]).filter(f=>f.parent_id===folderId);const files=(data?.resources||[]).filter(r=>r.folder_id===folderId).filter(r=>`${r.title} ${r.file_name||''} ${r.subject||''}`.toLowerCase().includes(query.toLowerCase()));
  const breadcrumbs=useMemo(()=>{const out:FolderRow[]=[];let id=folderId;while(id&&data){const f=data.folders.find(x=>x.id===id);if(!f)break;out.unshift(f);id=f.parent_id;}return out},[folderId,data]);
  async function jsonAction(body:Record<string,unknown>){setBusy(true);setError('');setMessage('');try{const t=await token();const r=await fetch(`/api/resources-v14/?mode=${mode}`,{method:'POST',headers:{Authorization:`Bearer ${t}`,'Content-Type':'application/json'},body:JSON.stringify(body)});const p=await r.json();if(!r.ok)throw new Error(p.error||'Resource action failed.');setMessage('Saved successfully.');await load();return true}catch(e){setError(e instanceof Error?e.message:'Resource action failed.');return false}finally{setBusy(false)}}
  async function upload(){if(!file)return;setBusy(true);setError('');setMessage('');try{const t=await token();const form=new FormData();form.set('file',file);form.set('folderId',folderId||'');form.set('title',draft.title||file.name);form.set('subject',draft.subject);form.set('gradeMin',draft.gradeMin);form.set('gradeMax',draft.gradeMax);form.set('description',draft.description);const r=await fetch(`/api/resources-v14/?mode=${mode}`,{method:'POST',headers:{Authorization:`Bearer ${t}`},body:form});const p=await r.json();if(!r.ok)throw new Error(p.error||'Upload failed.');setUploadOpen(false);setFile(null);setDraft({title:'',subject:'General',gradeMin:'1',gradeMax:'12',description:''});setMessage('Resource uploaded to Cloudflare R2.');await load();}catch(e){setError(e instanceof Error?e.message:'Upload failed.')}finally{setBusy(false)}}
  if(loading)return <div className="p-6 text-sm text-[var(--muted-foreground)]"><LoaderCircle className="mr-2 inline h-4 w-4 animate-spin"/>Loading resource library…</div>;
  return <div className="space-y-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-[var(--teal)]">Structured Resources</p><h1 className="mt-2 text-2xl font-bold text-[var(--foreground)]">{mode==='platform'?'Evidara Resources':mode==='student'?'Your Resources':'School Resources'}</h1><p className="mt-1 text-sm text-[var(--muted-foreground)]">Folders and subfolders can be organized by class, subject and chapter. Accepted uploads include PDF, Word, PowerPoint, Excel, CSV, text and common image formats.</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={()=>void load()}><RefreshCw className="mr-2 h-4 w-4"/>Refresh</Button>{canManageHere&&<><Button variant="outline" onClick={()=>setFolderOpen(true)}><FolderPlus className="mr-2 h-4 w-4"/>New folder</Button><Button onClick={()=>setUploadOpen(true)} className="bg-[var(--teal)] text-white"><Upload className="mr-2 h-4 w-4"/>Upload file</Button></>}</div></div>
    {error&&<div className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}{message&&<div className="rounded-xl border border-[var(--secondary)] bg-[var(--canvas)] p-3 text-sm text-[var(--teal)]">{message}</div>}
    <div className="flex flex-wrap items-center gap-2 text-sm">{folderId&&<Button size="sm" variant="ghost" onClick={()=>setFolderId(currentFolder?.parent_id||null)}><ChevronLeft className="mr-1 h-4 w-4"/>Back</Button>}<button className="font-semibold text-[var(--teal)]" onClick={()=>setFolderId(null)}>Root</button>{breadcrumbs.map(f=><span key={f.id} className="flex items-center gap-2"><span className="text-[#AEB8BC]">/</span><button onClick={()=>setFolderId(f.id)} className="font-medium text-[var(--muted-foreground)]">{f.name}</button></span>)}</div>
    <div className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-[var(--muted-foreground)]"/><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search files in this folder" className="pl-9"/></div>
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{childFolders.map(f=><Card key={f.id} className="cursor-pointer hover:border-[var(--teal)]" onClick={()=>setFolderId(f.id)}><CardContent className="p-4"><div className="flex items-start justify-between"><Folder className="h-7 w-7 text-[var(--amber)]"/>{data?.canManage&& (mode==='platform' ? f.resource_scope==='platform' : f.resource_scope==='organization') &&<Button variant="ghost" size="icon" onClick={async e=>{e.stopPropagation();if(confirm(`Delete folder ${f.name}?`))await jsonAction({action:'deleteFolder',folderId:f.id})}}><Trash2 className="h-4 w-4 text-[var(--destructive)]"/></Button>}</div><strong className="mt-3 block text-[var(--foreground)]">{f.name}</strong><p className="mt-1 text-xs text-[var(--muted-foreground)]">{[f.class_level,f.subject,f.chapter].filter(Boolean).join(' · ')||'Folder'}</p></CardContent></Card>)}{files.map(r=><Card key={r.id} className="shadow-sm rounded-xl"><CardContent className="flex h-full flex-col p-4"><div className="flex items-start justify-between"><FileText className="h-7 w-7 text-[var(--teal)]"/>{data?.canManage&&r.resource_scope!=='platform'&&mode!=='platform'?<Button variant="ghost" size="icon" onClick={async()=>{if(confirm('Remove this resource?'))await jsonAction({action:'deleteResource',resourceId:r.id})}}><Trash2 className="h-4 w-4 text-[var(--destructive)]"/></Button>:data?.canManage&&mode==='platform'?<Button variant="ghost" size="icon" onClick={async()=>{if(confirm('Remove this Evidara resource?'))await jsonAction({action:'deleteResource',resourceId:r.id})}}><Trash2 className="h-4 w-4 text-[var(--destructive)]"/></Button>:null}</div><strong className="mt-3 line-clamp-2 text-[var(--foreground)]">{r.title}</strong><p className="mt-1 text-xs text-[var(--muted-foreground)]">{r.file_name||r.subject||'Resource'} · {fmtBytes(Number(r.size_bytes||0))}</p><p className="mt-1 text-[11px] text-[#87949A]">{r.resource_scope==='platform'?'Published by Evidara':'Published by your institution'}</p><div className="mt-auto pt-4">{r.content_url?<Button asChild className="w-full bg-[var(--teal)] text-white"><a href={r.content_url} target="_blank" rel="noreferrer"><Download className="mr-2 h-4 w-4"/>Open / Download</a></Button>:<Button disabled className="w-full" variant="outline">File unavailable</Button>}</div></CardContent></Card>)}</div>
    {!childFolders.length&&!files.length&&<Card className="shadow-sm rounded-xl"><CardContent className="p-10 text-center text-sm text-[var(--muted-foreground)]">This folder is empty.{data?.canManage?' Create a folder or upload a file to begin.':''}</CardContent></Card>}
    <Dialog open={folderOpen} onOpenChange={setFolderOpen}><DialogContent><DialogHeader><DialogTitle>Create folder</DialogTitle><DialogDescription>Use class, subject and chapter labels to keep the resource tree easy to navigate.</DialogDescription></DialogHeader><div className="grid gap-3 sm:grid-cols-2"><div className="sm:col-span-2"><Label>Folder name</Label><Input className="mt-1" value={folderDraft.name} onChange={e=>setFolderDraft({...folderDraft,name:e.target.value})}/></div><div><Label>Class</Label><Input className="mt-1" value={folderDraft.classLevel} onChange={e=>setFolderDraft({...folderDraft,classLevel:e.target.value})} placeholder="e.g. Grade 11"/></div><div><Label>Subject</Label><Input className="mt-1" value={folderDraft.subject} onChange={e=>setFolderDraft({...folderDraft,subject:e.target.value})}/></div><div className="sm:col-span-2"><Label>Chapter</Label><Input className="mt-1" value={folderDraft.chapter} onChange={e=>setFolderDraft({...folderDraft,chapter:e.target.value})}/></div></div><DialogFooter><Button variant="outline" onClick={()=>setFolderOpen(false)}>Cancel</Button><Button disabled={!folderDraft.name.trim()||busy} onClick={async()=>{if(await jsonAction({action:'createFolder',parentId:folderId,...folderDraft})){setFolderDraft({name:'',classLevel:'',subject:'',chapter:''});setFolderOpen(false)}}} className="bg-[var(--teal)] text-white">Create</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={uploadOpen} onOpenChange={setUploadOpen}><DialogContent><DialogHeader><DialogTitle>Upload resource</DialogTitle><DialogDescription>The file will be stored in Cloudflare R2 and linked to the current folder.</DialogDescription></DialogHeader><div className="space-y-3"><Input type="file" accept=".pdf,.doc,.docx,.ppt,.pptx,.xls,.xlsx,.csv,.txt,image/*" onChange={e=>{const f=e.target.files?.[0]||null;setFile(f);if(f&&!draft.title)setDraft({...draft,title:f.name})}}/><div><Label>Title</Label><Input className="mt-1" value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></div><div><Label>Subject</Label><Input className="mt-1" value={draft.subject} onChange={e=>setDraft({...draft,subject:e.target.value})}/></div><div className="grid grid-cols-2 gap-3"><div><Label>Grade from</Label><Input type="number" min="1" max="12" className="mt-1" value={draft.gradeMin} onChange={e=>setDraft({...draft,gradeMin:e.target.value})}/></div><div><Label>Grade to</Label><Input type="number" min="1" max="12" className="mt-1" value={draft.gradeMax} onChange={e=>setDraft({...draft,gradeMax:e.target.value})}/></div></div><div><Label>Description</Label><Input className="mt-1" value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/></div></div><DialogFooter><Button variant="outline" onClick={()=>setUploadOpen(false)}>Cancel</Button><Button disabled={!file||busy} onClick={()=>void upload()} className="bg-[var(--teal)] text-white">{busy?<LoaderCircle className="mr-2 h-4 w-4 animate-spin"/>:<Upload className="mr-2 h-4 w-4"/>}Upload</Button></DialogFooter></DialogContent></Dialog>
  </div>
}
