"use client";
import { useMemo, useState } from "react";
import { Ban, CheckCircle2, Filter, GraduationCap, LockKeyhole, Plus, Search, UserMinus, Users } from "lucide-react";
import { promoteAllStudents, promoteStudent, revokeAllStudents, revokeStudent, SchoolBoard, StudentTrack } from "@/lib/schoolPlatform";
import { useSchoolPlatform } from "./useSchoolPlatform";

const tracks: StudentTrack[] = ["Foundation","Boards","Olympiad","NEET","JEE","KCET"];
export function StudentLifecycleManager() {
  const { state, update, ready } = useSchoolPlatform();
  const [query,setQuery]=useState(""); const [status,setStatus]=useState("all"); const [targetYear,setTargetYear]=useState("2027-28"); const [showAdd,setShowAdd]=useState(false);
  const filtered=useMemo(()=>state.students.filter(s=>(status==="all"||s.status===status)&&(s.name+" "+s.grade+" "+s.section).toLowerCase().includes(query.toLowerCase())),[state.students,status,query]);
  if(!ready)return <div className="so-card so-pad">Loading students…</div>;
  function addStudent(form:FormData){const name=String(form.get("name")||"").trim();if(!name)return;const next={id:`st-${Date.now()}`,name,grade:Number(form.get("grade")||8),section:String(form.get("section")||"A"),board:state.school.board as SchoolBoard,academicYear:"2026-27",tracks:form.getAll("tracks") as StudentTrack[],status:"active" as const,promotionLocked:false,parentName:String(form.get("parent")||""),parentPhone:String(form.get("phone")||"")};update(current=>({...current,students:[...current.students,next]}));setShowAdd(false)}
  function changeTracks(id:string,track:StudentTrack){update(current=>({...current,students:current.students.map(s=>s.id!==id?s:{...s,tracks:s.tracks.includes(track)?s.tracks.filter(x=>x!==track):[...s.tracks,track]})}))}
  const active=state.students.filter(s=>s.status==="active").length, revoked=state.students.filter(s=>s.status==="revoked").length, completed=state.students.filter(s=>s.status==="completed").length;
  return <div><div className="so-page-head"><div><span className="so-kicker">ACADEMIC-YEAR ROLLOVER</span><h1>Student lifecycle and promotion</h1><p>Promote individuals or the eligible roster. Revoked students stay locked and are never included in Promote All.</p></div><button className="so-btn so-btn-primary" onClick={()=>setShowAdd(v=>!v)}><Plus size={17}/> Add student</button></div>
    <div className="so-grid so-grid-4"><div className="so-stat"><Users/><strong>{state.students.length}</strong><span>Total records</span></div><div className="so-stat"><CheckCircle2/><strong>{active}</strong><span>Active</span></div><div className="so-stat"><LockKeyhole/><strong>{revoked}</strong><span>Revoked and locked</span></div><div className="so-stat"><GraduationCap/><strong>{completed}</strong><span>Completed Grade 12</span></div></div>
    <section className="so-card so-pad so-mt rollover-panel"><div><span className="so-kicker">TARGET ACADEMIC YEAR</span><select className="so-input" value={targetYear} onChange={e=>setTargetYear(e.target.value)}><option>2027-28</option><option>2028-29</option><option>2029-30</option></select></div><div className="so-action-row"><button className="so-btn so-btn-primary" onClick={()=>{if(confirm(`Promote all eligible active students to ${targetYear}? Revoked students will remain excluded.`))update(s=>promoteAllStudents(s,targetYear))}}><GraduationCap size={17}/> Promote all eligible</button><button className="so-btn so-btn-danger" onClick={()=>{if(confirm("Revoke every currently active student? This locks them out of future bulk promotion."))update(current=>revokeAllStudents(current))}}><UserMinus size={17}/> Revoke all active</button></div></section>
    <div className="so-notice warning so-mt"><Ban/> <span><strong>Permanent bulk exclusion:</strong> once a student is revoked, Promote All will not add or promote that student again. There is no bulk restore action.</span></div>
    {showAdd&&<form className="so-card so-pad so-mt" onSubmit={e=>{e.preventDefault();addStudent(new FormData(e.currentTarget))}}><div className="so-form-grid"><label>Name<input className="so-input" name="name" required/></label><label>Grade<select className="so-input" name="grade">{[8,9,10,11,12].map(g=><option key={g}>{g}</option>)}</select></label><label>Section<input className="so-input" name="section" defaultValue="A"/></label><label>Parent name<input className="so-input" name="parent"/></label><label>Parent phone<input className="so-input" name="phone"/></label><div><span className="so-field-label">Preparation tracks</span><div className="track-checks">{tracks.map(t=><label key={t}><input type="checkbox" name="tracks" value={t}/>{t}</label>)}</div></div></div><button className="so-btn so-btn-primary" style={{marginTop:14}}>Create student record</button></form>}
    <div className="so-toolbar so-mt"><div className="so-search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search student, grade or section"/></div><div className="so-filter"><Filter size={16}/><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All statuses</option><option value="active">Active</option><option value="revoked">Revoked</option><option value="completed">Completed</option></select></div></div>
    <div className="so-card so-table-wrap"><table className="so-table"><thead><tr><th>Student</th><th>Current year</th><th>Grade</th><th>Eligibility tracks</th><th>Status</th><th>Actions</th></tr></thead><tbody>{filtered.map(s=><tr key={s.id}><td><strong>{s.name}</strong><small>{s.parentName} · {s.parentPhone}</small></td><td>{s.academicYear}</td><td>Grade {s.grade}-{s.section}</td><td><div className="track-pills">{tracks.map(t=><button type="button" key={t} disabled={s.status!=="active"} onClick={()=>changeTracks(s.id,t)} className={s.tracks.includes(t)?"active":""}>{t}</button>)}</div></td><td><span className={`so-status ${s.status==="active"?"success":s.status==="revoked"?"danger":"neutral"}`}>{s.status}</span>{s.promotionLocked&&<small><LockKeyhole size={12}/> promotion locked</small>}</td><td><div className="so-action-row">{s.status==="active"&&<><button className="so-btn so-btn-small so-btn-primary" onClick={()=>update(current=>promoteStudent(current,s.id,targetYear))}><GraduationCap size={14}/> Promote</button><button className="so-btn so-btn-small so-btn-danger" onClick={()=>{if(confirm(`Revoke ${s.name}? This permanently excludes the record from bulk promotion.`))update(current=>revokeStudent(current,s.id))}}><UserMinus size={14}/> Revoke</button></>}{s.status==="revoked"&&<span className="locked-copy"><LockKeyhole size={14}/> Locked from bulk promotion</span>}{s.status==="completed"&&<span className="locked-copy"><GraduationCap size={14}/> Academic cycle complete</span>}</div></td></tr>)}</tbody></table></div>
  </div>
}
