import Link from "next/link";
import { ArrowRight, BarChart3, BookOpenCheck, ClipboardCheck, FileSpreadsheet, GraduationCap, LockKeyhole, RefreshCw, ShieldCheck, Sparkles, Users } from "lucide-react";
import { Navbar } from "@/components/Navbar";
import { Logo } from "@/components/Logo";

export default function Home(){return <><Navbar/><main>
<section className="public-hero"><div className="rm-container hero-grid"><div className="hero-copy"><span className="so-label included">EVIDENCE-DRIVEN STUDENT DEVELOPMENT</span><h1>Every assessment should lead to a clearer next step.</h1><p>Evidara brings school-created assessments, previous-year resources, secure online exams, student intelligence and annual roster management into one subscription-based school platform.</p><div className="hero-actions"><Link href="/school/register/" className="so-btn so-btn-primary">Start a school pilot <ArrowRight size={17}/></Link><Link href="/login/" className="rm-btn-secondary">Open product demo</Link></div><div className="hero-proof"><div><strong>₹0</strong><span>PER SCHOOL-CREATED TEST</span></div><div><strong>8–12</strong><span>GRADE ELIGIBILITY</span></div><div><strong>One plan</strong><span>ANNUAL SCHOOL ACCESS</span></div></div></div><div className="product-preview"><div className="preview-top"><span>Evidara · Student Development Evidence</span><span>Current cycle</span></div><div className="preview-body"><div className="preview-metrics"><div><strong>91st</strong><span>STUDENT PERCENTILE</span></div><div><strong>84%</strong><span>LATEST ACCURACY</span></div><div><strong>+26</strong><span>SCORE IMPROVEMENT</span></div></div><div className="preview-chart">{[42,65,52,81,68,92,77,98,86].map((height,index)=><i key={index} style={{height:`${height}%`}}/>)}</div></div></div></div></section>
<section id="platform" className="public-section alt"><div className="rm-container"><div className="section-head"><span className="so-kicker">ASSESS · UNDERSTAND · GUIDE · DEVELOP</span><h2>A complete assessment operating system</h2><p>The integrated testing platform is presented through the Evidara identity while retaining the current school-first functionality.</p></div><div className="feature-grid">{[
{icon:FileSpreadsheet,title:"Question bank and imports",body:"Manual MCQ, numerical and multi-correct creation with LaTeX, images, CSV, XLSX and image ZIP imports."},
{icon:ClipboardCheck,title:"Flexible paper builder",body:"Sections, chapter filters, auto, hybrid and manual selection, difficulty mix, marks, negative marks and scheduling."},
{icon:ShieldCheck,title:"Secure test delivery",body:"Autosave, timer, question palette, review flags, access codes, attempt limits, fullscreen and violation events."},
{icon:BarChart3,title:"Student intelligence",body:"Accuracy, speed, error causes, topic mastery, cognitive skill, improvement trends and teacher-ready next actions."},
{icon:Users,title:"Student lifecycle",body:"Individual promotion, Promote All, individual revoke and Revoke All with permanent exclusion of revoked records."},
{icon:BookOpenCheck,title:"Eligibility-controlled resources",body:"State, CBSE, ICSE and ISC board papers plus NEET, JEE, KCET, Foundation and Olympiad access by grade and track."}
].map(({icon:Icon,title,body})=><article className="feature-card" key={title}><Icon/><h3>{title}</h3><p>{body}</p></article>)}</div></div></section>
<section id="schools" className="public-section"><div className="rm-container"><div className="section-head"><span className="so-kicker">BUILT FOR SCHOOL OPERATIONS</span><h2>Free tests. Complimentary resources. Clear access rules.</h2><p>Schools subscribe annually. Their own tests carry no additional per-test fee, while previous-year papers are complimentary resources available during an active subscription.</p></div><div className="so-grid so-grid-3"><article className="so-card so-pad benefit-card"><span className="so-label free">FREE</span><ClipboardCheck/><h3>School-created assessments</h3><p>Teachers can build chapter, subject, mixed and full-length papers without buying each test separately.</p></article><article className="so-card so-pad benefit-card"><span className="so-label complimentary">COMPLIMENTARY</span><Sparkles/><h3>Previous-year papers</h3><p>Board and entrance-exam resources unlock during an active annual subscription and remain eligibility-controlled.</p></article><article className="so-card so-pad benefit-card"><span className="so-label included">CONTROLLED</span><LockKeyhole/><h3>Grade and track eligibility</h3><p>A Grade 10 State Board student receives the correct board papers; Grade 11–12 students receive only assigned NEET, JEE or KCET resources.</p></article></div></div></section>
<section id="analytics" className="public-section alt"><div className="rm-container"><div className="pricing-story"><div><span className="so-kicker light">STUDENT INTELLIGENCE</span><h2>See beyond marks.</h2><p>Evidara identifies whether marks were lost through concept gaps, methods, avoidable errors, interpretation or time pressure—and converts those findings into practical teacher and student actions.</p><Link href="/student/analytics/" className="so-btn so-btn-accent">View analytics experience <ArrowRight size={16}/></Link></div><div className="pricing-points"><div><span>Topic and chapter mastery</span><strong>Heatmaps + trends</strong></div><div><span>Speed vs expected time</span><strong>Per question</strong></div><div><span>Error classification</span><strong>5 cause groups</strong></div><div><span>Teacher intervention</span><strong>Small-group actions</strong></div><div><span>Retesting discipline</span><strong>7 and 21 days</strong></div></div></div></div></section>
<section id="subscription" className="public-section"><div className="rm-container"><div className="section-head"><span className="so-kicker">ANNUAL SUBSCRIPTION MODEL</span><h2>Renew the school, promote eligible students and leave revoked records behind.</h2><p>Before the next academic year, schools can revoke students who left, promote one student, promote all remaining eligible students, or revoke all. Bulk promotion never restores a revoked student.</p></div><div className="so-grid so-grid-3"><article className="feature-card"><RefreshCw/><h3>Annual renewal</h3><p>Subscription dates, seat capacity and resource entitlement are tracked at school level.</p></article><article className="feature-card"><GraduationCap/><h3>Promotion controls</h3><p>Promote individuals or the active roster to the next academic year with Grade 12 completion handling.</p></article><article className="feature-card"><LockKeyhole/><h3>Permanent revoke lock</h3><p>Revoked students are excluded from every future Promote All operation.</p></article></div></div></section>
</main><footer className="public-footer"><div className="rm-container footer-inner"><Logo/><div>Evidence-driven assessment and student development for Grades 8–12.</div><div>© 2026 Evidara</div></div></footer></>}
