import Link from "next/link";
import { ArrowRight, BarChart3, BookOpenCheck, Brain, ClipboardCheck, FileSpreadsheet, GitCompareArrows, GraduationCap, LockKeyhole, RefreshCw, ShieldCheck, Sparkles, Users } from "lucide-react";
import { Navbar } from "@/components/Navbar";
import { Logo } from "@/components/Logo";

export default function Home(){return <><Navbar/><main>
<section className="public-hero"><div className="rm-container hero-grid"><div className="hero-copy"><span className="so-label included">EVIDENCE-DRIVEN STUDENT DEVELOPMENT</span><h1>See beyond marks.</h1><p>Evidara helps schools assess, understand, guide and improve. It combines school-created tests, anonymous shared-paper benchmarks, responsible student intelligence and annual academic workflows in one platform.</p><div className="hero-actions"><Link href="/school/register/" className="so-btn so-btn-primary">Start a school pilot <ArrowRight size={17}/></Link><Link href="/login/" className="rm-btn-secondary">Explore the product</Link></div><div className="hero-proof"><div><strong>₹0</strong><span>PER SCHOOL-CREATED TEST</span></div><div><strong>Private</strong><span>SHARED BENCHMARKS</span></div><div><strong>One plan</strong><span>ANNUAL SCHOOL ACCESS</span></div></div></div><div className="product-preview"><div className="preview-top"><span>Evidara · Student evidence</span><span>Current cycle</span></div><div className="preview-body"><div className="preview-metrics"><div><strong>91st</strong><span>PRIVATE PERCENTILE</span></div><div><strong>84%</strong><span>LATEST ACCURACY</span></div><div><strong>+26</strong><span>IMPROVEMENT TREND</span></div></div><div className="preview-chart">{[42,65,52,81,68,92,77,98,86].map((height,index)=><i key={index} style={{height:`${height}%`}}/>)}</div></div></div></div></section>
<section id="platform" className="public-section alt"><div className="rm-container"><div className="section-head"><span className="so-kicker">ASSESS → UNDERSTAND → GUIDE → DEVELOP</span><h2>Evidence becomes a practical next step</h2><p>Every assessment signal is explained, placed in context and connected to an action for the student, teacher or school leader.</p></div><div className="feature-grid">{[
{icon:FileSpreadsheet,title:"Question bank and imports",body:"Manual, Excel, CSV, image, ZIP and LaTeX-aware workflows for school and licensed question banks."},
{icon:ClipboardCheck,title:"Flexible paper builder",body:"Auto, hybrid and manual selection with sections, difficulty, marks, schedules and secure delivery."},
{icon:GitCompareArrows,title:"Anonymous shared benchmarks",body:"Share the same paper widely and compare aggregate evidence without publishing a student or school identity."},
{icon:BarChart3,title:"Explained student intelligence",body:"Every trend, percentile, segment, speed and mastery measure includes its meaning, evidence window and responsible-use note."},
{icon:Users,title:"Student lifecycle",body:"Promote eligible students and permanently exclude revoked records from later bulk promotion."},
{icon:BookOpenCheck,title:"Eligibility-controlled resources",body:"Board, NEET, JEE, KCET, Foundation and Olympiad resources unlock by subscription, grade and assigned track."}
].map(({icon:Icon,title,body})=><article className="feature-card" key={title}><Icon/><h3>{title}</h3><p>{body}</p></article>)}</div></div></section>
<section id="schools" className="public-section"><div className="rm-container"><div className="section-head"><span className="so-kicker">ONE PAPER · BROADER CONTEXT · PRIVATE IDENTITIES</span><h2>Understand where your cohort stands</h2><p>A participating school sees its own named learners and a private cohort percentile. The shared view shows only sample size and aggregate distributions after the privacy threshold is reached.</p></div><div className="so-grid so-grid-3"><article className="so-card so-pad benefit-card"><span className="so-label free">SHARE</span><GitCompareArrows/><h3>Exact paper version</h3><p>Duration, marks, question version and scoring stay identical so the comparison is meaningful.</p></article><article className="so-card so-pad benefit-card"><span className="so-label complimentary">PRIVATE</span><ShieldCheck/><h3>No school leaderboard</h3><p>School names, contacts, student identities and response sheets are excluded from the public benchmark.</p></article><article className="so-card so-pad benefit-card"><span className="so-label included">ACTION</span><Brain/><h3>Move beyond the rank</h3><p>Use subject, topic, accuracy and pacing evidence to decide what teaching support should happen next.</p></article></div><div style={{textAlign:"center",marginTop:24}}><Link href="/school/benchmarks/" className="so-btn so-btn-primary">Explore a shared benchmark <ArrowRight size={16}/></Link></div></div></section>
<section id="analytics" className="public-section alt"><div className="rm-container"><div className="pricing-story"><div><span className="so-kicker light">STUDENT INTELLIGENCE</span><h2>Every metric should explain itself.</h2><p>Evidara shows what a measure means, how much evidence it uses, why it is useful and what it cannot responsibly claim. Segments are temporary action groups, never labels of ability.</p><Link href="/student/analytics/" className="so-btn so-btn-accent">View the evidence <ArrowRight size={16}/></Link></div><div className="pricing-points"><div><span>Improvement trend</span><strong>Latest comparable cycles</strong></div><div><span>Shared percentile</span><strong>Same paper only</strong></div><div><span>Topic mastery</span><strong>Recency + difficulty</strong></div><div><span>Student segment</span><strong>Transparent rules</strong></div><div><span>Recommended action</span><strong>One owner · one date</strong></div></div></div></div></section>
<section id="subscription" className="public-section"><div className="rm-container"><div className="section-head"><span className="so-kicker">ANNUAL SUBSCRIPTION MODEL</span><h2>Free tests. Complimentary resources. Controlled access.</h2><p>Schools subscribe annually. Their own tests carry no per-test fee; previous-year papers are complimentary plan resources for eligible students.</p></div><div className="so-grid so-grid-3"><article className="feature-card"><RefreshCw/><h3>Annual renewal</h3><p>Subscription dates, seat capacity and resource entitlements stay auditable.</p></article><article className="feature-card"><GraduationCap/><h3>Promotion controls</h3><p>Promote individuals or the active roster with Grade 12 completion handling.</p></article><article className="feature-card"><LockKeyhole/><h3>Permanent revoke lock</h3><p>Revoked students remain excluded from future bulk and individual promotion.</p></article></div></div></section>
</main><footer className="public-footer"><div className="rm-container footer-inner"><Logo reversed/><div>Evidence that helps schools guide every student forward.</div><div>© 2026 Evidara</div></div></footer></>}
