"use client";
import { useCallback, useEffect, useState } from "react";
import { Edit3, LoaderCircle, PackagePlus, RefreshCw } from "lucide-react";
import { supabase } from "@/lib/supabase";
import { discountPercent, rupees } from "@/types/commerce";

const emptyForm = {
  id: "", name: "", slug: "", short_description: "", description: "", product_type: "test_series",
  audience: "student", exam_type: "NEET", mrp_rupees: "5999", selling_rupees: "1999", access_days: "365",
  max_attempts: "20", student_limit: "", features: "Full-length mock tests\nSubject and chapter analytics\nMobile access",
  status: "draft", is_featured: false,
};
type Form = typeof emptyForm;
type AdminProduct = { id:string;name:string;slug:string;short_description:string|null;description:string|null;product_type:string;audience:string;exam_type:string|null;status:string;is_featured:boolean;product_versions:Array<{id:string;mrp_paise:number;selling_price_paise:number;access_days:number|null;max_attempts:number|null;student_limit:number|null;features:string[];is_current:boolean;version_number:number}> };
const slugify=(s:string)=>s.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");

export function AdminProductManager(){
 const [form,setForm]=useState<Form>(emptyForm);const [products,setProducts]=useState<AdminProduct[]>([]);const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");
 const load=useCallback(async()=>{if(!supabase)return;setBusy(true);const {data,error}=await supabase.from("products").select("id,name,slug,short_description,description,product_type,audience,exam_type,status,is_featured,product_versions(id,mrp_paise,selling_price_paise,access_days,max_attempts,student_limit,features,is_current,version_number)").order("created_at",{ascending:false});if(error)setMessage(error.message);else setProducts((data??[]) as AdminProduct[]);setBusy(false)},[]);
 useEffect(()=>{void load()},[load]);
 const set=(k:keyof Form,v:string|boolean)=>setForm(p=>({...p,[k]:v}));
 function edit(p:AdminProduct){const v=p.product_versions.find(x=>x.is_current)??p.product_versions[0];setForm({id:p.id,name:p.name,slug:p.slug,short_description:p.short_description??"",description:p.description??"",product_type:p.product_type,audience:p.audience,exam_type:p.exam_type??"",mrp_rupees:String((v?.mrp_paise??0)/100),selling_rupees:String((v?.selling_price_paise??0)/100),access_days:v?.access_days?String(v.access_days):"",max_attempts:v?.max_attempts?String(v.max_attempts):"",student_limit:v?.student_limit?String(v.student_limit):"",features:(v?.features??[]).join("\n"),status:p.status,is_featured:p.is_featured});window.scrollTo({top:0,behavior:"smooth"})}
 async function save(e:React.FormEvent){e.preventDefault();setMessage("");if(!supabase){setMessage("Connect Supabase before creating live products.");return;}setBusy(true);const features=form.features.split("\n").map(x=>x.trim()).filter(Boolean);const {error}=await supabase.rpc("admin_upsert_product",{p_product_id:form.id||null,p_name:form.name,p_slug:form.slug||slugify(form.name),p_short_description:form.short_description||null,p_description:form.description||null,p_product_type:form.product_type,p_audience:form.audience,p_exam_type:form.exam_type||null,p_mrp_paise:Math.round(Number(form.mrp_rupees)*100),p_selling_price_paise:Math.round(Number(form.selling_rupees)*100),p_access_days:form.access_days?Number(form.access_days):null,p_max_attempts:form.max_attempts?Number(form.max_attempts):null,p_student_limit:form.student_limit?Number(form.student_limit):null,p_features:features,p_status:form.status,p_is_featured:form.is_featured});if(error)setMessage(error.message);else{setMessage(form.id?"Product updated with a new price/version record.":"Product created successfully.");setForm(emptyForm);await load()}setBusy(false)}
 const mrp=Math.round(Number(form.mrp_rupees||0)*100),selling=Math.round(Number(form.selling_rupees||0)*100);
 return <div><form onSubmit={save} className="rm-card" style={{padding:22}}><div style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"center",marginBottom:18,flexWrap:"wrap"}}><div><span className="rm-label">Product builder</span><h2 style={{margin:"5px 0"}}>{form.id?"Edit product and create new version":"Create a paid product"}</h2></div>{form.id&&<button type="button" className="rm-btn-secondary" onClick={()=>setForm(emptyForm)}>Create another</button>}</div>
 <div className="admin-form-grid" style={{display:"grid",gridTemplateColumns:"repeat(2,minmax(0,1fr))",gap:14}}>
  <label style={{gridColumn:"1/-1"}}><span className="rm-label">Product name</span><input className="rm-input" value={form.name} onChange={e=>{set("name",e.target.value);if(!form.id)set("slug",slugify(e.target.value))}} required/></label>
  <label><span className="rm-label">Slug</span><input className="rm-input" value={form.slug} onChange={e=>set("slug",slugify(e.target.value))} required/></label>
  <label><span className="rm-label">Exam type</span><input className="rm-input" value={form.exam_type} onChange={e=>set("exam_type",e.target.value)} placeholder="NEET, JEE Main, KCET…"/></label>
  <label><span className="rm-label">Product type</span><select className="rm-input" value={form.product_type} onChange={e=>set("product_type",e.target.value)}>{["single_exam","test_series","subject_package","chapter_package","entrance_exam","student_subscription","school_subscription","question_bank_addon","bundle"].map(x=><option key={x} value={x}>{x.replaceAll("_"," ")}</option>)}</select></label>
  <label><span className="rm-label">Audience</span><select className="rm-input" value={form.audience} onChange={e=>set("audience",e.target.value)}><option value="student">Student</option><option value="school">School</option><option value="both">Both</option></select></label>
  <label style={{gridColumn:"1/-1"}}><span className="rm-label">Short description</span><input className="rm-input" value={form.short_description} onChange={e=>set("short_description",e.target.value)}/></label>
  <label style={{gridColumn:"1/-1"}}><span className="rm-label">Full description</span><textarea className="rm-input" rows={3} value={form.description} onChange={e=>set("description",e.target.value)}/></label>
  <label><span className="rm-label">List price ₹</span><input type="number" min="0" step="1" className="rm-input" value={form.mrp_rupees} onChange={e=>set("mrp_rupees",e.target.value)} required/></label>
  <label><span className="rm-label">Selling price ₹</span><input type="number" min="0" step="1" className="rm-input" value={form.selling_rupees} onChange={e=>set("selling_rupees",e.target.value)} required/></label>
  <div style={{gridColumn:"1/-1",background:"#f8fafc",padding:12,borderRadius:12,fontWeight:750}}>Store preview: <s>{rupees(mrp)}</s> &nbsp; <strong>{rupees(selling)}</strong> &nbsp; {discountPercent(mrp,selling)}% OFF</div>
  <label><span className="rm-label">Access days</span><input type="number" className="rm-input" value={form.access_days} onChange={e=>set("access_days",e.target.value)}/></label>
  <label><span className="rm-label">Maximum attempts</span><input type="number" className="rm-input" value={form.max_attempts} onChange={e=>set("max_attempts",e.target.value)}/></label>
  <label><span className="rm-label">School student limit</span><input type="number" className="rm-input" value={form.student_limit} onChange={e=>set("student_limit",e.target.value)} placeholder="Leave blank for student products"/></label>
  <label><span className="rm-label">Status</span><select className="rm-input" value={form.status} onChange={e=>set("status",e.target.value)}><option value="draft">Draft</option><option value="published">Published</option><option value="archived">Archived</option></select></label>
  <label style={{gridColumn:"1/-1"}}><span className="rm-label">Features — one per line</span><textarea className="rm-input" rows={5} value={form.features} onChange={e=>set("features",e.target.value)}/></label>
  <label style={{gridColumn:"1/-1",display:"flex",gap:9,alignItems:"center",fontWeight:750}}><input type="checkbox" checked={form.is_featured} onChange={e=>set("is_featured",e.target.checked)}/>Show as featured product</label>
 </div><button disabled={busy} className="rm-btn-primary" style={{marginTop:18,display:"flex",gap:8,alignItems:"center",justifyContent:"center",width:"100%"}}>{busy?<LoaderCircle size={18} className="spin"/>:<PackagePlus size={18}/>} {form.id?"Save new product version":"Create product"}</button>{message&&<div style={{marginTop:14,padding:12,borderRadius:10,background:"#fff7dc"}}>{message}</div>}<style jsx>{`@media(max-width:650px){.admin-form-grid{grid-template-columns:1fr!important}.admin-form-grid>*{grid-column:1!important}}`}</style></form>
 <section className="rm-card" style={{padding:20,marginTop:20}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><div><span className="rm-label">Live catalogue</span><h2>Products and current pricing</h2></div><button className="rm-btn-secondary" onClick={load}><RefreshCw size={16}/></button></div><div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",minWidth:760}}><thead><tr style={{textAlign:"left",color:"#667085"}}><th style={{padding:10}}>Product</th><th>Audience</th><th>Status</th><th>Current price</th><th>Version</th><th></th></tr></thead><tbody>{products.map(p=>{const v=p.product_versions.find(x=>x.is_current)??p.product_versions[0];return <tr key={p.id} style={{borderTop:"1px solid #eef1f5"}}><td style={{padding:12}}><strong>{p.name}</strong><div style={{fontSize:12,color:"#667085"}}>{p.slug}</div></td><td>{p.audience}</td><td>{p.status}</td><td>{v?rupees(v.selling_price_paise):"No price"}</td><td>{v?`v${v.version_number}`:"—"}</td><td><button className="rm-btn-secondary" onClick={()=>edit(p)}><Edit3 size={15}/> Edit</button></td></tr>})}</tbody></table>{!products.length&&!busy&&<p style={{color:"#667085"}}>No live products yet. Run the seed SQL or create your first product above.</p>}</div></section></div>
}
