'use client';

import { useEffect, useState } from 'react';
import { Copy, Gift, RefreshCcw, Share2, WalletCards } from 'lucide-react';
import { supabase } from '@/lib/supabase';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';

const rupees=(paise:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format((paise||0)/100);

type Summary={code:string;balance_paise:number;total_earned_paise:number;successful_referrals:number;pending_referrals:number};

export function ReferralCenter(){
  const [summary,setSummary]=useState<Summary|null>(null);const [loading,setLoading]=useState(true);const [message,setMessage]=useState('');const [schoolStudent,setSchoolStudent]=useState(false);
  async function load(){setLoading(true);setMessage('');if(!supabase){setMessage('Connect Supabase to use referrals.');setLoading(false);return;}const {data:session}=await supabase.auth.getUser();const uid=session.user?.id;if(uid){const {data:membership}=await supabase.from('student_school_memberships').select('id').eq('student_id',uid).eq('status','active').limit(1).maybeSingle();if(membership){setSchoolStudent(true);setSummary(null);setLoading(false);return;}setSchoolStudent(false);}const {data,error}=await supabase.rpc('get_my_referral_summary');if(error){setMessage(error.message);setSummary(null);}else{const row=Array.isArray(data)?data[0]:data;setSummary(row?{code:String(row.code),balance_paise:Number(row.balance_paise||0),total_earned_paise:Number(row.total_earned_paise||0),successful_referrals:Number(row.successful_referrals||0),pending_referrals:Number(row.pending_referrals||0)}:null);}setLoading(false)}
  useEffect(()=>{void load()},[]);
  async function copy(){if(!summary)return;const url=`${window.location.origin}/products/?ref=${encodeURIComponent(summary.code)}`;await navigator.clipboard.writeText(url);setMessage('Referral link copied.');}
  async function share(){if(!summary)return;const url=`${window.location.origin}/products/?ref=${encodeURIComponent(summary.code)}`;if(navigator.share){await navigator.share({title:'Evidara Test Series',text:'Join Evidara using my referral link.',url});}else await copy();}
  if(loading)return <div className="p-6 text-sm text-[var(--muted-foreground)]">Loading referral wallet…</div>;
  if(schoolStudent)return <Card className="shadow-sm rounded-xl"><CardContent className="p-4 sm:p-5 lg:p-6"><h2 className="font-semibold text-[var(--foreground)]">Referral promotion is for direct Evidara students</h2><p className="mt-2 text-sm leading-6 text-[var(--muted-foreground)]">Your school enrolment already includes institution benefits and self-assessment credits, so the public Refer & Earn promotion is intentionally disabled for school-enrolled students.</p></CardContent></Card>;
  if(!summary)return <Card className="shadow-sm rounded-xl"><CardContent className="p-4 sm:p-5 lg:p-6"><h2 className="font-semibold">Referral wallet unavailable</h2><p className="mt-2 text-sm text-[var(--muted-foreground)]">{message||'Please try again.'}</p><Button className="mt-4" variant="outline" onClick={()=>void load()}><RefreshCcw className="mr-2 h-4 w-4"/>Retry</Button></CardContent></Card>;
  return <div className="space-y-6"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-[var(--teal)]">Evidara referrals</p><h1 className="mt-2 text-3xl font-bold text-[var(--foreground)]">Invite friends. Earn Evidara credit.</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-[var(--muted-foreground)]">A referral is rewarded only after the referred student completes their first qualifying paid individual purchase. Credits never change exam results or entitlements.</p></div>
  {message&&<div className="rounded-xl border border-[var(--secondary)] bg-white px-4 py-3 text-sm text-[#44545C]">{message}</div>}
  <div className="grid gap-3 sm:gap-4 lg:gap-5 md:grid-cols-4"><Card className="shadow-sm rounded-xl"><CardContent className="p-4 sm:p-5 lg:p-6"><WalletCards className="h-5 w-5 text-[var(--teal)]"/><p className="mt-4 text-xs text-[var(--muted-foreground)]">Available credit</p><strong className="mt-1 block text-2xl text-[var(--foreground)]">{rupees(summary.balance_paise)}</strong></CardContent></Card><Card className="shadow-sm rounded-xl"><CardContent className="p-4 sm:p-5 lg:p-6"><Gift className="h-5 w-5 text-[var(--teal)]"/><p className="mt-4 text-xs text-[var(--muted-foreground)]">Total earned</p><strong className="mt-1 block text-2xl text-[var(--foreground)]">{rupees(summary.total_earned_paise)}</strong></CardContent></Card><Card className="shadow-sm rounded-xl"><CardContent className="p-4 sm:p-5 lg:p-6"><Share2 className="h-5 w-5 text-[var(--teal)]"/><p className="mt-4 text-xs text-[var(--muted-foreground)]">Successful referrals</p><strong className="mt-1 block text-2xl text-[var(--foreground)]">{summary.successful_referrals}</strong></CardContent></Card><Card className="shadow-sm rounded-xl"><CardContent className="p-4 sm:p-5 lg:p-6"><RefreshCcw className="h-5 w-5 text-[var(--teal)]"/><p className="mt-4 text-xs text-[var(--muted-foreground)]">Pending</p><strong className="mt-1 block text-2xl text-[var(--foreground)]">{summary.pending_referrals}</strong></CardContent></Card></div>
  <Card className="shadow-sm rounded-xl"><CardContent className="p-4 sm:p-5 lg:p-6"><p className="text-xs font-semibold uppercase tracking-wide text-[var(--muted-foreground)]">Your code</p><div className="mt-3 flex flex-col gap-3 sm:flex-row sm:items-center"><div className="rounded-xl border border-dashed border-[var(--teal)]/35 bg-[var(--secondary)]/40 px-5 py-3 font-mono text-xl font-bold tracking-widest text-[var(--teal)]">{summary.code}</div><Button onClick={()=>void copy()} variant="outline"><Copy className="mr-2 h-4 w-4"/>Copy link</Button><Button onClick={()=>void share()} className="bg-[var(--teal)] text-white"><Share2 className="mr-2 h-4 w-4"/>Share</Button></div><p className="mt-4 text-xs leading-5 text-[var(--muted-foreground)]">Current program rule: the first qualifying individual purchase must be at least ₹1,000. When it succeeds, both the referring student and the new student receive ₹100 Evidara credit.</p></CardContent></Card></div>;
}
