import Link from "next/link";
import { BarChart3, Building2, ClipboardList, CreditCard, FileQuestion, GitCompareArrows, Package, ShieldCheck, Sparkles, Upload, Users } from "lucide-react";
import { DashboardShell } from "@/components/DashboardShell";
import { ProtectedPage } from "@/components/ProtectedPage";
import { MetricLabel } from "@/components/ui/MetricInfo";
import { metricDefinitions } from "@/lib/evidaraMetrics";

export default function AdminDashboard(){return <ProtectedPage allowed="admin"><DashboardShell kind="admin"><div className="so-page-head"><div><span className="so-kicker">PLATFORM COMMAND CENTRE</span><h1>Evidara operations</h1><p>Manage annual school access, master academic content, privacy-safe shared benchmarks, secure examinations and the evidence layer.</p></div><div className="so-action-row"><Link href="/admin/questions/import/" className="rm-btn-secondary"><Upload size={17}/>Import questions</Link><Link href="/admin/papers/new/" className="so-btn so-btn-primary">Create master paper</Link></div></div>
<div className="so-grid so-grid-4"><div className="so-stat"><Building2/><strong>4</strong><span>School accounts</span></div><div className="so-stat"><CreditCard/><strong>2</strong><span>Active annual plans</span></div><div className="so-stat"><Users/><strong>2,063</strong><span>Students covered</span></div><div className="so-stat"><GitCompareArrows/><strong>12,842</strong><span><MetricLabel {...metricDefinitions.benchmark}>benchmark attempts</MetricLabel></span></div></div>
<div className="so-grid so-grid-2 so-mt"><section className="so-card so-pad"><div className="so-section-head"><div><span className="so-kicker">SUBSCRIPTION OPERATIONS</span><h2>Renewals and seat governance</h2></div><CreditCard/></div><p style={{color:"#6B7980",lineHeight:1.6}}>Control school start dates, expiry, seat capacity, suspension and resource access. Expired schools retain records but lose publishing and complimentary-resource access.</p><Link href="/admin/subscriptions/" className="so-btn so-btn-primary">Manage school subscriptions</Link></section><section className="so-card so-pad"><div className="so-section-head"><div><span className="so-kicker">RESPONSIBLE PRODUCT LANGUAGE</span><h2>Free, complimentary and private</h2></div><Sparkles/></div><div className="so-steps"><div><b>F</b><span><strong>Free school-created tests</strong><small>No per-test charge during the annual subscription.</small></span></div><div><b>C</b><span><strong>Complimentary previous papers</strong><small>Unlocked only for subscribed, eligible students.</small></span></div><div><b>P</b><span><strong>Private shared benchmarks</strong><small>Aggregate context without public school or student identities.</small></span></div></div></section></div>
<div className="so-grid so-grid-3 so-mt">{[
{icon:FileQuestion,title:"Master question bank",text:"Question types, LaTeX, images, taxonomy, duplicate detection, review and versions.",href:"/admin/questions/"},
{icon:ClipboardList,title:"Assessment catalogue",text:"Sections, marks, difficulty, access, schedules, secure attempts and automatic evaluation.",href:"/admin/papers/"},
{icon:Package,title:"Plans and pricing",text:"Annual school products, current price versions, entitlements and payment records.",href:"/admin/products/"},
{icon:BarChart3,title:"Explained evidence",text:"Transparent metrics, evidence windows, temporary segments and next actions.",href:"/student/analytics/"},
{icon:Building2,title:"School boundaries",text:"Private school questions remain isolated while master content is licensed safely.",href:"/admin/subscriptions/"},
{icon:ShieldCheck,title:"System and security",text:"Validate database policies, answer-key restrictions, benchmark privacy and deployment readiness.",href:"/setup-check/"}
].map(({icon:Icon,title,text,href})=><Link href={href} key={title} className="so-card so-pad insight-card"><Icon/><span className="so-kicker">PLATFORM MODULE</span><h3>{title}</h3><p>{text}</p></Link>)}</div>
</DashboardShell></ProtectedPage>}
