import Link from "next/link";
import { BarChart3, Building2, CircleHelp, ClipboardList, CreditCard, FileQuestion, Package, ShieldCheck, Sparkles, Upload, Users } from "lucide-react";
import { DashboardShell } from "@/components/DashboardShell";
import { ProtectedPage } from "@/components/ProtectedPage";
import { MetricLabel } from "@/components/ui/MetricInfo";
import { metricDefinitions } from "@/lib/evidaraMetrics";

export default function AdminDashboard(){return <ProtectedPage allowed="admin"><DashboardShell kind="admin"><div className="so-page-head"><div><span className="so-kicker">PLATFORM COMMAND CENTRE</span><h1>Evidara operations</h1><p>Manage annual school access, master academic content, secure examinations and the student-intelligence layer.</p><Link href="/metric-guide/" className="ev-guide-link"><CircleHelp size={16}/>How Evidara calculates these metrics</Link></div><div className="so-action-row"><Link href="/admin/readiness/" className="rm-btn-secondary"><ShieldCheck size={17}/>Run launch checks</Link><Link href="/admin/questions/import/" className="rm-btn-secondary"><Upload size={17}/>Import questions</Link><Link href="/admin/papers/new/" className="so-btn so-btn-primary">Create master paper</Link></div></div>
<div className="so-grid so-grid-4"><div className="so-stat"><Building2/><strong>4</strong><span><MetricLabel {...metricDefinitions.schoolAccounts}>School accounts</MetricLabel></span></div><div className="so-stat"><CreditCard/><strong>2</strong><span><MetricLabel {...metricDefinitions.activePlans}>Active annual plans</MetricLabel></span></div><div className="so-stat"><Users/><strong>2,063</strong><span><MetricLabel {...metricDefinitions.studentsCovered}>Students covered</MetricLabel></span></div><div className="so-stat"><ClipboardList/><strong>18</strong><span><MetricLabel {...metricDefinitions.publishedAssessments}>Published assessments</MetricLabel></span></div></div>
<div className="so-grid so-grid-2 so-mt"><section className="so-card so-pad"><div className="so-section-head"><div><span className="so-kicker">SUBSCRIPTION OPERATIONS</span><h2>Renewals and seat governance</h2></div><CreditCard/></div><p style={{color:"#6B7980",lineHeight:1.6}}>Control school start dates, expiry, seat capacity, suspension and resource access. Expired schools retain their records but lose publishing and complimentary-resource access.</p><Link href="/admin/subscriptions/" className="so-btn so-btn-primary">Manage school subscriptions</Link></section><section className="so-card so-pad"><div className="so-section-head"><div><span className="so-kicker">PRODUCT LANGUAGE</span><h2>Free and complimentary are not the same</h2></div><Sparkles/></div><div className="so-steps"><div><b>F</b><span><strong>Free school-created tests</strong><small>No additional per-test charge during the annual subscription.</small></span></div><div><b>C</b><span><strong>Complimentary previous papers</strong><small>Unlocked only for subscribed, eligible students.</small></span></div></div></section></div>
<div className="so-grid so-grid-3 so-mt">{[
{icon:FileQuestion,title:"Master question bank",text:"Question types, LaTeX, images, taxonomy, duplicate detection, review and versions.",href:"/admin/questions/"},
{icon:ClipboardList,title:"Assessment catalogue",text:"Sections, marks, difficulty, access, schedules, secure attempts and automatic evaluation.",href:"/admin/papers/"},
{icon:Package,title:"Plans and pricing",text:"Annual school products, current price versions, entitlements and payment records.",href:"/admin/products/"},
{icon:BarChart3,title:"Student intelligence",text:"Score, speed, mastery, error causes, trends and intervention actions.",href:"/student/analytics/"},
{icon:Building2,title:"School boundaries",text:"Private school questions remain isolated while master content is licensed safely.",href:"/admin/subscriptions/"},
{icon:ShieldCheck,title:"Launch readiness",text:"Run V6.8 Supabase, Auth, migration 24, Razorpay Test Mode and protected-route diagnostics.",href:"/admin/readiness/"}
].map(({icon:Icon,title,text,href})=><Link href={href} key={title} className="so-card so-pad insight-card"><Icon/><span className="so-kicker">EVIDARA MODULE</span><h3>{title}</h3><p>{text}</p></Link>)}</div>
</DashboardShell></ProtectedPage>}
