"use client";
import { Activity, Brain, CheckCircle2, Clock3, Gauge, Lightbulb, Target, TrendingUp, TriangleAlert } from "lucide-react";
import { CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";

const trend=[{test:"T1",score:58,accuracy:61,speed:54},{test:"T2",score:64,accuracy:68,speed:59},{test:"T3",score:71,accuracy:74,speed:66},{test:"T4",score:78,accuracy:81,speed:70},{test:"T5",score:84,accuracy:86,speed:76}];
const topics=[{name:"Cell Biology",mastery:92,status:"Strong"},{name:"Chemical Bonding",mastery:78,status:"Improving"},{name:"Kinematics",mastery:63,status:"Needs practice"},{name:"Ratio & Proportion",mastery:57,status:"Priority"},{name:"Data Interpretation",mastery:72,status:"Improving"}];
const errors=[{label:"Concept gap",value:36},{label:"Wrong method",value:24},{label:"Careless error",value:20},{label:"Time pressure",value:12},{label:"Guessing",value:8}];

export function StudentIntelligence(){return <div><div className="so-page-head"><div><span className="so-kicker">POST-TEST INTELLIGENCE</span><h1>Complete student analytics</h1><p>A teacher-ready explanation of what the learner knows, where marks are lost and exactly what should happen next.</p></div><span className="so-status success">5 tests analysed</span></div>
  <section className="analytics-command"><div><span className="so-kicker light">CURRENT READINESS</span><h2>High potential, accuracy becoming stable</h2><p>The learner has improved consistently across five assessments. Ratio and time-bound Physics remain the main barriers to the next performance band.</p><div className="so-inline-stats"><div><strong>84%</strong><span>latest accuracy</span></div><div><strong>91st</strong><span>percentile</span></div><div><strong>+26</strong><span>score gain</span></div><div><strong>76</strong><span>speed index</span></div></div></div><div className="readiness-ring"><strong>82</strong><span>readiness index</span></div></section>
  <div className="so-grid so-grid-4 so-mt"><div className="so-stat"><CheckCircle2/><strong>42/50</strong><span>Correct answers</span></div><div className="so-stat"><Clock3/><strong>68 sec</strong><span>Average per question</span></div><div className="so-stat"><Gauge/><strong>6</strong><span>Overtime questions</span></div><div className="so-stat"><TriangleAlert/><strong>8</strong><span>Recoverable marks</span></div></div>
  <div className="so-grid so-grid-2 so-mt"><section className="so-card so-pad"><div className="so-section-head"><div><span className="so-kicker">IMPROVEMENT TREND</span><h2>Score, accuracy and speed</h2></div><TrendingUp/></div><div style={{height:280}}><ResponsiveContainer width="100%" height="100%"><LineChart data={trend}><CartesianGrid strokeDasharray="3 3" stroke="#e5e9f0"/><XAxis dataKey="test"/><YAxis domain={[40,100]}/><Tooltip/><Line type="monotone" dataKey="score" stroke="#18b7a0" strokeWidth={3}/><Line type="monotone" dataKey="accuracy" stroke="#7456e8" strokeWidth={2}/><Line type="monotone" dataKey="speed" stroke="#ef9c3f" strokeWidth={2}/></LineChart></ResponsiveContainer></div></section>
  <section className="so-card so-pad"><div className="so-section-head"><div><span className="so-kicker">ERROR CAUSES</span><h2>Why marks were lost</h2></div><Brain/></div><div className="error-bars">{errors.map(e=><div key={e.label}><div><span>{e.label}</span><strong>{e.value}%</strong></div><i><b style={{width:`${e.value}%`}}/></i></div>)}</div><div className="so-notice warning"><Lightbulb/><span>Concept gap is the largest loss source. Do not solve more mixed papers until the two priority concepts are repaired.</span></div></section></div>
  <div className="so-grid so-grid-2 so-mt"><section className="so-card so-pad"><div className="so-section-head"><div><span className="so-kicker">TOPIC MASTERY</span><h2>Evidence by concept</h2></div><Activity/></div><div className="mastery-list">{topics.map(t=><div key={t.name}><div><strong>{t.name}</strong><span>{t.status}</span></div><i><b style={{width:`${t.mastery}%`}}/></i><small>{t.mastery}% current mastery</small></div>)}</div></section>
  <section className="so-card so-pad"><div className="so-section-head"><div><span className="so-kicker">PROFESSOR ACTION PLAN</span><h2>What to do next</h2></div><Target/></div><div className="so-steps"><div><b>1</b><span><strong>Repair Ratio & Proportion</strong><small>Watch one worked explanation, then complete 12 controlled questions without a timer.</small></span></div><div><b>2</b><span><strong>Run a Kinematics speed set</strong><small>Complete 15 medium questions with a 75-second cap and record skipped steps.</small></span></div><div><b>3</b><span><strong>Retest after seven days</strong><small>Require at least 80% accuracy and no more than two careless errors.</small></span></div><div><b>4</b><span><strong>Retention check after 21 days</strong><small>Verify that the improvement survives a delay and an unfamiliar question format.</small></span></div></div></section></div>
  <div className="so-grid so-grid-3 so-mt"><article className="so-card so-pad insight-card"><Brain/><span className="so-kicker">COGNITIVE PROFILE</span><h3>Application strong; analysis improving</h3><p>Recall is not the main issue. Most lost marks occur when the learner must select a multi-step method quickly.</p></article><article className="so-card so-pad insight-card"><Clock3/><span className="so-kicker">TIME BEHAVIOUR</span><h3>Slow start, efficient finish</h3><p>The first five questions consume 22% more time. A structured first-pass strategy should recover exam time.</p></article><article className="so-card so-pad insight-card"><Target/><span className="so-kicker">TEACHER INTERVENTION</span><h3>Small-group method clinic</h3><p>Place the learner with students showing the same procedural error, not with every student scoring below average.</p></article></div>
  </div>}
