"use client";

import Link from "next/link";
import { Activity, Brain, CheckCircle2, CircleHelp, Clock3, Gauge, Lightbulb, Target, TrendingUp, TriangleAlert } from "lucide-react";
import { CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { MetricInfo, MetricLabel } from "@/components/ui/MetricInfo";
import { metricDefinitions, segmentDefinitions } from "@/lib/evidaraMetrics";

const trend=[
  {test:"12 May",score:58,accuracy:61,speed:54},
  {test:"28 May",score:64,accuracy:68,speed:59},
  {test:"11 Jun",score:71,accuracy:74,speed:66},
  {test:"27 Jun",score:78,accuracy:81,speed:70},
  {test:"14 Jul",score:84,accuracy:86,speed:76},
];
const topics=[{name:"Cell Biology",mastery:92,status:"Strong"},{name:"Chemical Bonding",mastery:78,status:"Improving"},{name:"Kinematics",mastery:63,status:"Needs practice"},{name:"Ratio & Proportion",mastery:57,status:"Priority"},{name:"Data Interpretation",mastery:72,status:"Improving"}];
const errors=[{label:"Concept gap",value:36},{label:"Wrong method",value:24},{label:"Avoidable error",value:20},{label:"Time pressure",value:12},{label:"Guessing",value:8}];

export function StudentIntelligence(){const segment=segmentDefinitions.fast_improver;return <div>
  <div className="so-page-head"><div><span className="so-kicker">STUDENT EVIDENCE</span><h1>Progress, context and the next step</h1><p>Each measure explains what it means, how it was evaluated and what it can responsibly support. Current evidence covers five comparable assessments from 12 May to 14 July.</p><Link href="/metric-guide/" className="ev-guide-link"><CircleHelp size={16}/>Open the complete metric guide</Link></div><span className="so-status success">5 assessments analysed</span></div>

  <section className="analytics-command"><div><span className="so-kicker light">CURRENT DEVELOPMENT SEGMENT</span><div className="ev-dark-metric-title"><h2>{segment.label}</h2><MetricInfo {...metricDefinitions.segment}/></div><p>{segment.rule}</p><div className="so-inline-stats"><div><strong>84%</strong><span><MetricLabel {...metricDefinitions.score}>latest score</MetricLabel></span></div><div><strong>91st</strong><span><MetricLabel {...metricDefinitions.percentile}>percentile</MetricLabel></span></div><div><strong>+26</strong><span><MetricLabel {...metricDefinitions.trend}>score gain</MetricLabel></span></div><div><strong>76</strong><span><MetricLabel {...metricDefinitions.speed}>speed index</MetricLabel></span></div></div></div><div className="readiness-ring"><strong>82</strong><span><MetricLabel {...metricDefinitions.readiness}>readiness index</MetricLabel></span></div></section>

  <div className="so-grid so-grid-4 so-mt"><div className="so-stat"><CheckCircle2/><strong>42/50</strong><span><MetricLabel {...metricDefinitions.correctAnswers}>Correct answers</MetricLabel></span></div><div className="so-stat"><Clock3/><strong>68 sec</strong><span><MetricLabel {...metricDefinitions.averageQuestionTime}>Average per question</MetricLabel></span></div><div className="so-stat"><Gauge/><strong>6</strong><span><MetricLabel {...metricDefinitions.overtimeQuestions}>Overtime questions</MetricLabel></span></div><div className="so-stat"><TriangleAlert/><strong>8</strong><span><MetricLabel {...metricDefinitions.recoverableMarks}>Recoverable marks</MetricLabel></span></div></div>

  <div className="so-grid so-grid-2 so-mt"><section className="so-card so-pad"><div className="so-section-head"><div><span className="so-kicker">IMPROVEMENT TREND</span><h2>Score, accuracy and speed</h2><small className="ev-evidence-window">Five comparable assessments · 12 May–14 July · minimum three required</small></div><MetricInfo {...metricDefinitions.trend}/></div><div style={{height:280}}><ResponsiveContainer width="100%" height="100%"><LineChart data={trend}><CartesianGrid strokeDasharray="3 3" stroke="#E7ECEB"/><XAxis dataKey="test"/><YAxis domain={[40,100]}/><Tooltip/><Line type="monotone" dataKey="score" name="Score" stroke="#0E5A5A" strokeWidth={3}/><Line type="monotone" dataKey="accuracy" name="Accuracy" stroke="#2E6D8B" strokeWidth={2}/><Line type="monotone" dataKey="speed" name="Speed index" stroke="#F2B84B" strokeWidth={2}/></LineChart></ResponsiveContainer></div><div className="so-notice info"><Lightbulb/><span>The direction is positive across all three measures. Continue the current plan, then verify that the improvement remains after a 21-day delay.</span></div></section>
  <section className="so-card so-pad"><div className="so-section-head"><div><span className="so-kicker">ERROR CAUSES</span><h2>Why marks were lost</h2><small className="ev-evidence-window">Based on 22 incorrect or overtime responses in the latest paper</small></div><MetricInfo {...metricDefinitions.errorCauses}/></div><div className="error-bars">{errors.map(error=><div key={error.label}><div><span>{error.label}</span><strong>{error.value}%</strong></div><i><b style={{width:`${error.value}%`}}/></i></div>)}</div><div className="so-notice warning"><Lightbulb/><span>Concept gap is the largest observed loss source. Repair the two priority concepts before adding another mixed full-length paper.</span></div></section></div>

  <div className="so-grid so-grid-2 so-mt"><section className="so-card so-pad"><div className="so-section-head"><div><span className="so-kicker">TOPIC MASTERY</span><h2>Evidence by concept</h2><small className="ev-evidence-window">Recency and difficulty weighted · minimum five valid responses per topic</small></div><MetricInfo {...metricDefinitions.mastery}/></div><div className="mastery-list">{topics.map(topic=><div key={topic.name}><div><strong>{topic.name}</strong><span>{topic.status}</span></div><i><b style={{width:`${topic.mastery}%`}}/></i><small>{topic.mastery}% current mastery</small></div>)}</div></section>
  <section className="so-card so-pad"><div className="so-section-head"><div><span className="so-kicker">SEGMENT DEFINITION</span><h2>Why “{segment.label}” appears</h2></div><MetricInfo {...metricDefinitions.segment}/></div><div className="ev-segment-definition"><span>Current rule</span><p>{segment.rule}</p><span>Recommended next action</span><p>{segment.nextAction}</p><span>Recalculation</span><p>After every valid comparable assessment. The segment can change as new evidence becomes available.</p></div><div className="so-notice info"><Brain/><span>This segment describes the current evidence pattern. It is not a permanent judgement of ability, intelligence, potential or future outcome.</span></div></section></div>

  <section className="so-card so-pad so-mt"><div className="so-section-head"><div><span className="so-kicker">DEVELOPMENT PLAN</span><h2>What to do next</h2></div><Target/></div><div className="so-steps"><div><b>1</b><span><strong>Repair Ratio & Proportion</strong><small>Watch one worked explanation, then complete 12 controlled questions without a timer.</small></span></div><div><b>2</b><span><strong>Run a Kinematics speed set</strong><small>Complete 15 medium questions with a 75-second cap and record skipped steps.</small></span></div><div><b>3</b><span><strong>Retest after seven days</strong><small>Look for at least 80% accuracy and no more than two avoidable errors.</small></span></div><div><b>4</b><span><strong>Retention check after 21 days</strong><small>Verify that the change survives a delay and an unfamiliar question format.</small></span></div></div></section>

  <div className="so-grid so-grid-3 so-mt"><article className="so-card so-pad insight-card"><Brain/><span className="so-kicker">COGNITIVE EVIDENCE</span><h3>Application strong; analysis improving</h3><p>Recall is not the main issue. Most lost marks occur when the learner must select a multi-step method quickly.</p></article><article className="so-card so-pad insight-card"><Clock3/><span className="so-kicker">TIME BEHAVIOUR</span><h3>Slow start, efficient finish</h3><p>The first five questions consume 22% more time. A structured first-pass strategy should recover exam time.</p></article><article className="so-card so-pad insight-card"><Target/><span className="so-kicker">TEACHER ACTION</span><h3>Small-group method clinic</h3><p>Place the learner with students showing the same procedural need, not with every student scoring below average.</p></article></div>
</div>}
