"use client";
import { useEffect, useState } from "react";
import { CalendarClock, Clock3, FileQuestion, KeyRound, LoaderCircle, PlayCircle, RefreshCw, Sparkles } from "lucide-react";
import { supabase } from "@/lib/supabase";
import type { StudentPaperSummary } from "@/types/papers";

const demoPapers:StudentPaperSummary[]=[
{id:"demo-school",title:"Grade 10 Science Chapter Test",description:"A school-created test included without a per-test charge.",exam_type:"School MCQ",duration_minutes:30,total_marks:40,total_questions:10,attempt_limit:2,attempts_used:0,result_mode:"score_and_answers",access_mode:"organization",access_label:"free"},
{id:"demo-neet",title:"NEET 2025 Previous Year Practice",description:"A complimentary previous-year paper unlocked through the annual school subscription.",exam_type:"NEET",duration_minutes:180,total_marks:720,total_questions:180,attempt_limit:1,attempts_used:0,result_mode:"score_only",access_mode:"organization",access_label:"complimentary",is_previous_year_paper:true}
];
export function AvailableTests(){
 const [papers,setPapers]=useState<StudentPaperSummary[]>(demoPapers);const [code,setCode]=useState("");const [found,setFound]=useState<StudentPaperSummary|null>(null);const [loading,setLoading]=useState(Boolean(supabase));const [busy,setBusy]=useState("");const [error,setError]=useState("");
 async function load(){if(!supabase){setPapers(demoPapers);setLoading(false);return;}setLoading(true);const {data,error}=await supabase.rpc("list_available_papers");if(error)setError(error.message);else setPapers((data||[]) as StudentPaperSummary[]);setLoading(false)}
 useEffect(()=>{void load()},[]);
 async function findCode(){if(!supabase){const match=demoPapers.find(p=>code==="DEMO");if(match)setFound(match);else setError("Demo code: DEMO");return;}if(code.trim().length<4){setError("Enter the test access code.");return;}setError("");setBusy("code");const {data,error}=await supabase.rpc("find_paper_by_code",{p_code:code.trim()});if(error)setError(error.message);else if(!data)setError("No open test was found for this code.");else setFound(data as StudentPaperSummary);setBusy("")}
 async function start(paper:StudentPaperSummary,accessCode?:string){if(!supabase){window.location.assign("/trial/");return;}setBusy(paper.id);setError("");const {data,error}=await supabase.rpc("start_exam_attempt",{p_paper_id:paper.id,p_access_code:accessCode||null});if(error){setError(error.message);setBusy("");return;}window.location.assign(`/student/tests/take/?attempt=${String(data)}`)}
 const card=(paper:StudentPaperSummary,accessCode?:string)=>{const label=paper.access_label||"included";return <article key={paper.id} className="rm-card" style={{padding:18}}><div style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"start"}}><div><div style={{display:"flex",gap:7,flexWrap:"wrap"}}><span className="rm-label">{paper.exam_type}</span><span className={`so-label ${label}`}>{label.toUpperCase()}</span></div><h3 style={{margin:"8px 0",color:"#0b1324"}}>{paper.title}</h3><p style={{color:"#667085",fontSize:13,lineHeight:1.5}}>{paper.description||"Timed online examination"}</p></div><span className="rm-badge" style={{background:"#eef2f7",color:"#4f5d72"}}>{paper.access_mode}</span></div><div style={{display:"flex",gap:12,flexWrap:"wrap",fontSize:13,color:"#475467",marginTop:12}}><span><Clock3 size={15}/> {paper.duration_minutes} min</span><span><FileQuestion size={15}/> {paper.total_questions} questions</span><span>{paper.total_marks} marks</span></div>{paper.available_until&&<div style={{marginTop:10,fontSize:12,color:"#667085"}}><CalendarClock size={14}/> Closes {new Date(paper.available_until).toLocaleString()}</div>}<div style={{marginTop:14,display:"flex",justifyContent:"space-between",alignItems:"center",gap:10}}><span style={{fontSize:12,color:"#667085"}}>Attempts: {paper.attempts_used}/{paper.attempt_limit}</span><button className="rm-btn-primary" disabled={busy===paper.id||paper.attempts_used>=paper.attempt_limit} onClick={()=>start(paper,accessCode)}>{busy===paper.id?<LoaderCircle className="spin" size={16}/>:<PlayCircle size={16}/>}Start / Resume</button></div></article>};
 return <div><div className="so-page-head"><div><span className="so-kicker">ELIGIBLE ASSESSMENTS</span><h1>Available tests</h1><p>School-created tests are Free within the annual plan. Previous-year papers are shown as Complimentary.</p></div><button className="rm-btn-secondary" onClick={load}><RefreshCw size={16}/>Refresh</button></div>{error&&<div className="so-notice warning">{error}</div>}<section className="rm-card" style={{padding:17,marginTop:18}}><div style={{display:"grid",gridTemplateColumns:"1fr auto",gap:9}}><div style={{position:"relative"}}><KeyRound size={17} style={{position:"absolute",left:12,top:13,color:"#98a2b3"}}/><input className="rm-input" style={{paddingLeft:38}} placeholder="Enter private test code" value={code} onChange={e=>setCode(e.target.value.toUpperCase())}/></div><button className="rm-btn-dark" disabled={busy==="code"} onClick={findCode}>{busy==="code"?<LoaderCircle className="spin" size={16}/>:<KeyRound size={16}/>}Find test</button></div>{found&&<div style={{marginTop:14}}>{card(found,code)}</div>}</section><div className="so-notice info so-mt"><Sparkles/><span>Demo mode includes a working trial exam. Connect Supabase and apply the migrations for secure saved attempts, autosave and school-specific publishing.</span></div>{loading?<div style={{padding:45,textAlign:"center",color:"#667085"}}><LoaderCircle className="spin"/> Loading tests…</div>:<section className="test-grid" style={{display:"grid",gridTemplateColumns:"repeat(2,1fr)",gap:14,marginTop:18}}>{papers.length?papers.map(p=>card(p)):<div className="rm-card" style={{padding:42,textAlign:"center",gridColumn:"1/-1"}}><FileQuestion size={30} color="#98a2b3"/><h3>No open tests right now</h3><p style={{color:"#667085"}}>Published papers will appear here when their opening time is reached.</p></div>}</section>}<style>{`@media(max-width:760px){.test-grid{grid-template-columns:1fr!important}section[style*="1fr auto"]>div{grid-template-columns:1fr!important}}`}</style></div>
}
