"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import { BlockMath, InlineMath } from "react-katex";
import { AlertTriangle, CheckCircle2, ChevronLeft, ChevronRight, Clock3, Expand, LoaderCircle, Save, Send, Wifi } from "lucide-react";
import { supabase } from "@/lib/supabase";
import type { AttemptPayload } from "@/types/papers";

const hash=(value:string)=>{let h=2166136261;for(let i=0;i<value.length;i++){h^=value.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0};
const secondsText=(seconds:number)=>`${String(Math.floor(seconds/3600)).padStart(2,"0")}:${String(Math.floor((seconds%3600)/60)).padStart(2,"0")}:${String(seconds%60).padStart(2,"0")}`;

export function LiveExam(){
  const [payload,setPayload]=useState<AttemptPayload|null>(null);const [current,setCurrent]=useState(0);const [responses,setResponses]=useState<Record<string,unknown>>({});const [review,setReview]=useState<Record<string,boolean>>({});const [visited,setVisited]=useState<Record<string,boolean>>({});
  const [remaining,setRemaining]=useState(0);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [saveText,setSaveText]=useState("Ready");const [error,setError]=useState("");const [submitting,setSubmitting]=useState(false);const [result,setResult]=useState<Record<string,unknown>|null>(null);
  const enteredFullscreen=useRef(false);const submittingRef=useRef(false);const questionOpenedAt=useRef(Date.now());
  useEffect(()=>{const attempt=new URLSearchParams(window.location.search).get("attempt");if(!attempt){setError("Attempt ID is missing.");setLoading(false);return;}load(attempt)},[]);
  async function load(attempt:string){if(!supabase){setError("Connect Supabase to take this test.");setLoading(false);return;}const {data,error}=await supabase.rpc("get_exam_attempt_payload",{p_attempt_id:attempt});if(error){setError(error.message);setLoading(false);return;}const value=data as AttemptPayload;setPayload(value);const r:Record<string,unknown>={};const m:Record<string,boolean>={};const v:Record<string,boolean>={};value.responses.forEach(item=>{r[item.paper_question_id]=item.response;m[item.paper_question_id]=item.marked_for_review;v[item.paper_question_id]=item.visited});setResponses(r);setReview(m);setVisited({...v,[value.questions[0]?.paper_question_id]:true});setRemaining(Math.max(0,Math.floor((new Date(value.expires_at).getTime()-Date.now())/1000)));setLoading(false)}
  useEffect(()=>{if(!payload||result)return;const timer=setInterval(()=>{const seconds=Math.max(0,Math.floor((new Date(payload.expires_at).getTime()-Date.now())/1000));setRemaining(seconds);if(seconds===0&&!submittingRef.current){submittingRef.current=true;submit(true)}},1000);return()=>clearInterval(timer)},[payload,result]);
  useEffect(()=>{if(!payload||payload.status!=="in_progress")return;const record=(type:string)=>supabase?.rpc("record_exam_event",{p_attempt_id:payload.attempt_id,p_event_type:type,p_metadata:{at:new Date().toISOString()}});const hidden=()=>{if(document.hidden)record("tab_hidden")};const blur=()=>record("window_blur");const full=()=>{if(!document.fullscreenElement&&enteredFullscreen.current)record("fullscreen_exit")};document.addEventListener("visibilitychange",hidden);window.addEventListener("blur",blur);document.addEventListener("fullscreenchange",full);return()=>{document.removeEventListener("visibilitychange",hidden);window.removeEventListener("blur",blur);document.removeEventListener("fullscreenchange",full)}},[payload]);
  const question=payload?.questions[current];
  useEffect(()=>{questionOpenedAt.current=Date.now();if(question)setVisited(prev=>({...prev,[question.paper_question_id]:true}))},[current,question?.paper_question_id]);
  const orderedOptions=useMemo(()=>{if(!question)return[];const values=[...(question.options||[])];if(payload?.paper.shuffle_options)values.sort((a,b)=>hash(`${payload.attempt_id}-${question.paper_question_id}-${a.option_key}`)-hash(`${payload.attempt_id}-${question.paper_question_id}-${b.option_key}`));else values.sort((a,b)=>a.display_order-b.display_order);return values},[question,payload]);
  function answerArray(value:unknown){return Array.isArray(value)?value.map(String):value===null||value===undefined||value===""?[]:[String(value)]}
  async function saveAnswer(nextValue:unknown,nextReview=review[question?.paper_question_id||""]||false){if(!payload||!question||!supabase)return;setSaving(true);setSaveText("Saving…");const elapsed=Math.floor((Date.now()-questionOpenedAt.current)/1000);const {error}=await supabase.rpc("save_exam_response",{p_attempt_id:payload.attempt_id,p_paper_question_id:question.paper_question_id,p_response:nextValue===undefined?null:nextValue,p_marked_for_review:nextReview,p_time_spent_seconds:elapsed});if(error){setError(error.message);setSaveText("Save failed")}else setSaveText("Saved");setSaving(false)}
  async function selectOption(key:string){if(!question)return;const currentValue=answerArray(responses[question.paper_question_id]);let next:string[];if(question.question_type==="multiple_correct")next=currentValue.includes(key)?currentValue.filter(x=>x!==key):[...currentValue,key];else next=[key];setResponses(prev=>({...prev,[question.paper_question_id]:next}));await saveAnswer(next)}
  async function setNumeric(value:string){if(!question)return;setResponses(prev=>({...prev,[question.paper_question_id]:value}));setSaveText("Unsaved");}
  async function commitNumeric(){if(!question)return;await saveAnswer(responses[question.paper_question_id]??null)}
  async function toggleReview(){if(!question)return;const next=!review[question.paper_question_id];setReview(prev=>({...prev,[question.paper_question_id]:next}));await saveAnswer(responses[question.paper_question_id]??null,next)}
  function go(index:number){if(index<0||!payload||index>=payload.questions.length)return;if(question&&(question.question_type==="numerical"||question.question_type==="integer"))commitNumeric();setCurrent(index)}
  async function submit(automatic=false){if(!payload||!supabase||submitting)return;if(!automatic&&!window.confirm("Submit this test now? You cannot change answers after submission."))return;setSubmitting(true);submittingRef.current=true;setError("");if(question&&(question.question_type==="numerical"||question.question_type==="integer"))await commitNumeric();const {data,error}=await supabase.rpc("submit_exam_attempt",{p_attempt_id:payload.attempt_id});if(error){setError(error.message);setSubmitting(false);submittingRef.current=false;return;}setResult(data as Record<string,unknown>);setSubmitting(false)}
  async function enterFullscreen(){try{await document.documentElement.requestFullscreen();enteredFullscreen.current=true;await supabase?.rpc("record_exam_event",{p_attempt_id:payload?.attempt_id,p_event_type:"fullscreen_enter",p_metadata:{}})}catch{setError("Fullscreen could not be started. Continue in the current window.")}}
  if(loading)return <div style={{minHeight:"70vh",display:"grid",placeItems:"center",color:"#667085"}}><div style={{textAlign:"center"}}><LoaderCircle className="spin" size={30}/><h3>Preparing secure test session…</h3></div></div>;
  if(error&&!payload)return <div className="rm-card" style={{padding:30,maxWidth:700,margin:"40px auto",color:"#b42318"}}>{error}</div>;
  if(result)return <div className="rm-card" style={{padding:32,maxWidth:720,margin:"35px auto",textAlign:"center"}}><CheckCircle2 size={52} color="#137a3a"/><h1>Test submitted</h1><p style={{color:"#667085"}}>Your answers and result have been stored.</p><div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:10,marginTop:20}}>{[["Score",`${result.score}/${result.maximum_marks}`],["Percentage",`${result.percentage}%`],["Correct",result.correct_count],["Incorrect",result.incorrect_count]].map(([l,v])=><div key={String(l)} style={{padding:14,background:"#f8fafc",borderRadius:12}}><strong style={{fontSize:22}}>{String(v)}</strong><div style={{fontSize:12,color:"#667085"}}>{String(l)}</div></div>)}</div><a className="rm-btn-primary" href="/student/results/" style={{marginTop:22}}>View my results</a></div>;
  if(!payload||!question)return <div>No questions were found in this test.</div>;
  const currentAnswer=responses[question.paper_question_id];const answerKeys=answerArray(currentAnswer);
  const answeredCount=payload.questions.filter(q=>answerArray(responses[q.paper_question_id]).length>0).length;
  return <div style={{minHeight:"100vh",background:"#eef1f6"}}><header style={{position:"sticky",top:0,zIndex:20,background:"#131e35",color:"white",padding:"12px 18px",display:"flex",justifyContent:"space-between",gap:12,alignItems:"center",flexWrap:"wrap"}}><div><strong>{payload.paper.title}</strong><div style={{fontSize:11,color:"#c6d0e0"}}>{payload.paper.exam_type} · Attempt autosaves</div></div><div style={{display:"flex",gap:10,alignItems:"center"}}><button className="rm-btn-secondary" style={{padding:"8px 10px"}} onClick={enterFullscreen}><Expand size={15}/>Fullscreen</button><span style={{display:"inline-flex",alignItems:"center",gap:6,color:saving?"#ffd970":"#c6f6d5",fontSize:12}}>{saving?<LoaderCircle className="spin" size={14}/>:<Wifi size={14}/>} {saveText}</span><strong style={{fontSize:20,color:remaining<300?"#ffb4ab":"#ffd970"}}><Clock3 size={18}/> {secondsText(remaining)}</strong></div></header>
  {error&&<div style={{padding:10,background:"#fef3f2",color:"#b42318",textAlign:"center"}}><AlertTriangle size={15}/> {error}</div>}
  <div className="exam-layout" style={{display:"grid",gridTemplateColumns:"1fr 300px",gap:15,padding:15,maxWidth:1500,margin:"auto"}}><main className="rm-card" style={{padding:22,minWidth:0}}><div style={{display:"flex",justifyContent:"space-between",gap:12,borderBottom:"1px solid #e4e7ec",paddingBottom:13}}><div><span className="rm-label">Question {current+1} of {payload.questions.length}</span><div style={{fontSize:12,color:"#667085",marginTop:5}}>{payload.sections.find(s=>s.id===question.section_id)?.title||"Section"} · {question.question_type.replaceAll("_"," ")} · {question.difficulty.replaceAll("_"," ")}</div></div><strong style={{color:"#775600"}}>+{question.marks} / −{question.negative_marks}</strong></div>{question.passage_text&&<div style={{marginTop:16,padding:15,borderLeft:"4px solid #f6b100",background:"#fffaf0",whiteSpace:"pre-wrap",lineHeight:1.65}}>{question.passage_text}</div>}<h2 style={{fontSize:20,lineHeight:1.6,marginTop:18}}>{question.stem_text}</h2>{question.stem_latex&&<div style={{overflowX:"auto"}}><BlockMath math={question.stem_latex}/></div>}{question.question_image_url&&<img src={question.question_image_url} alt="Question diagram" style={{display:"block",maxWidth:"100%",maxHeight:380,objectFit:"contain",margin:"14px auto",borderRadius:12}}/>}
  {question.question_type==="numerical"||question.question_type==="integer"?<div style={{marginTop:20,maxWidth:380}}><span className="rm-label">Enter numerical answer</span><input type="number" step="any" className="rm-input" value={String(currentAnswer??"")} onChange={e=>setNumeric(e.target.value)} onBlur={commitNumeric} placeholder="Your answer" style={{marginTop:7,fontSize:18}}/></div>:<div style={{display:"grid",gap:10,marginTop:18}}>{orderedOptions.map(option=>{const checked=answerKeys.includes(option.option_key);return <button key={option.option_key} onClick={()=>selectOption(option.option_key)} style={{display:"grid",gridTemplateColumns:"38px 1fr",gap:10,alignItems:"center",textAlign:"left",padding:13,borderRadius:12,border:checked?"2px solid #f6b100":"1px solid #dfe4ec",background:checked?"#fff8e6":"white"}}><span style={{width:32,height:32,borderRadius:question.question_type==="multiple_correct"?8:999,display:"grid",placeItems:"center",background:checked?"#f6b100":"#f2f4f7",fontWeight:800}}>{option.option_key}</span><span>{option.content_text}{option.content_latex&&<span style={{marginLeft:6}}><InlineMath math={option.content_latex}/></span>}{option.image_url&&<img src={option.image_url} alt={`Option ${option.option_key}`} style={{display:"block",maxWidth:260,maxHeight:150,objectFit:"contain",marginTop:8}}/>}</span></button>})}</div>}
  <div style={{display:"flex",justifyContent:"space-between",gap:9,marginTop:24,flexWrap:"wrap"}}><button className="rm-btn-secondary" onClick={()=>go(current-1)} disabled={current===0}><ChevronLeft size={17}/>Previous</button><button className="rm-btn-secondary" onClick={toggleReview} style={{background:review[question.paper_question_id]?"#f4ebff":"white",color:review[question.paper_question_id]?"#6941c6":"#131e35"}}>Mark for review</button><button className="rm-btn-primary" onClick={()=>go(current+1)} disabled={current===payload.questions.length-1}>Save & next<ChevronRight size={17}/></button></div></main>
  <aside className="rm-card" style={{padding:16,height:"fit-content",position:"sticky",top:86}}><div style={{display:"flex",justifyContent:"space-between"}}><strong>Question palette</strong><span style={{fontSize:12,color:"#667085"}}>{answeredCount}/{payload.questions.length} answered</span></div><div style={{display:"grid",gridTemplateColumns:"repeat(5,1fr)",gap:7,marginTop:12}}>{payload.questions.map((q,index)=>{const answered=answerArray(responses[q.paper_question_id]).length>0;const marked=review[q.paper_question_id];const seen=visited[q.paper_question_id];return <button key={q.paper_question_id} onClick={()=>go(index)} style={{aspectRatio:"1",borderRadius:9,border:index===current?"3px solid #131e35":"1px solid #d0d5dd",background:marked?"#f4ebff":answered?"#ecfdf3":seen?"#fff8e6":"white",color:marked?"#6941c6":answered?"#137a3a":"#475467",fontWeight:800}}>{index+1}</button>})}</div><div style={{display:"grid",gap:6,fontSize:11,color:"#667085",marginTop:14}}><span><i style={{display:"inline-block",width:10,height:10,background:"#ecfdf3",marginRight:5}}/>Answered</span><span><i style={{display:"inline-block",width:10,height:10,background:"#f4ebff",marginRight:5}}/>Review</span><span><i style={{display:"inline-block",width:10,height:10,background:"#fff8e6",marginRight:5}}/>Visited</span></div><button className="rm-btn-dark" style={{width:"100%",marginTop:18}} disabled={submitting} onClick={()=>submit(false)}>{submitting?<LoaderCircle className="spin" size={17}/>:<Send size={17}/>}Submit test</button><div style={{fontSize:11,color:"#667085",marginTop:10,textAlign:"center"}}><Save size={12}/> Answers are stored in Supabase.</div></aside></div><style>{`@media(max-width:850px){.exam-layout{grid-template-columns:1fr!important}.exam-layout aside{position:relative!important;top:0!important}.exam-layout aside div:nth-child(2){grid-template-columns:repeat(8,1fr)!important}}@media(max-width:500px){.exam-layout{padding:8px!important}.exam-layout main{padding:15px!important}.exam-layout aside div:nth-child(2){grid-template-columns:repeat(5,1fr)!important}}`}</style></div>
}
