"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { ArrowLeft, CheckCircle2, Clock3, FileQuestion, LoaderCircle } from "lucide-react";
import { BlockMath, InlineMath } from "react-katex";
import { supabase } from "@/lib/supabase";

type PreviewItem={id:string;section_id:string;display_order:number;marks:number;negative_marks:number;question_snapshot:Record<string,unknown>};
type PreviewSection={id:string;title:string;instructions:string|null;questions_to_attempt:number|null;display_order:number};

export function PaperPreview({kind}:{kind:"admin"|"school"}){
  const [paper,setPaper]=useState<Record<string,unknown>|null>(null);const [sections,setSections]=useState<PreviewSection[]>([]);const [items,setItems]=useState<PreviewItem[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");
  const base=kind==="admin"?"/admin/papers":"/school/papers";
  useEffect(()=>{const id=new URLSearchParams(window.location.search).get("id");if(!id){setError("Paper ID is missing.");setLoading(false);return;}load(id)},[]);
  async function load(id:string){if(!supabase){setError("Connect Supabase to preview a saved paper.");setLoading(false);return;}const [{data:p,error:pErr},{data:s,error:sErr},{data:q,error:qErr}]=await Promise.all([supabase.from("question_papers").select("*").eq("id",id).single(),supabase.from("paper_sections").select("*").eq("paper_id",id).order("display_order"),supabase.from("paper_questions").select("id,section_id,display_order,marks,negative_marks,question_snapshot").eq("paper_id",id).order("display_order")]);if(pErr||sErr||qErr)setError(pErr?.message||sErr?.message||qErr?.message||"Unable to load paper.");else{setPaper(p);setSections((s||[]) as PreviewSection[]);setItems((q||[]) as PreviewItem[])}setLoading(false)}
  if(loading)return <div style={{padding:45,textAlign:"center",color:"#667085"}}><LoaderCircle className="spin"/> Loading paper preview…</div>;
  if(error||!paper)return <div><Link href={`${base}/`}><ArrowLeft size={16}/> Back to papers</Link><div style={{marginTop:15,padding:14,background:"#fef3f2",color:"#b42318",borderRadius:12}}>{error||"Paper not found."}</div></div>;
  return <div><div style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"end",flexWrap:"wrap"}}><div><Link href={`${base}/`} style={{display:"inline-flex",gap:7,alignItems:"center",fontWeight:700,color:"#667085"}}><ArrowLeft size={16}/>Back to papers</Link><span className="rm-label" style={{display:"block",marginTop:12}}>Administrator preview</span><h1 style={{margin:"5px 0",color:"#131e35"}}>{String(paper.title)}</h1><p style={{margin:0,color:"#667085"}}>{String(paper.description||"")}</p></div><Link className="rm-btn-primary" href={`${base}/new/?id=${String(paper.id)}`}>Edit paper</Link></div>
  <section className="rm-card" style={{padding:18,marginTop:18,display:"flex",gap:20,flexWrap:"wrap"}}><span><Clock3 size={16}/> {String(paper.duration_minutes)} minutes</span><span><FileQuestion size={16}/> {String(paper.total_questions)} questions</span><span><CheckCircle2 size={16}/> {String(paper.total_marks)} marks</span><span style={{textTransform:"capitalize"}}>Status: {String(paper.status)}</span><span>Access: {String(paper.access_mode)}</span></section>
  {Boolean(paper.instructions)&&<section className="rm-card" style={{padding:18,marginTop:14}}><span className="rm-label">Instructions</span><p style={{whiteSpace:"pre-wrap",lineHeight:1.6}}>{String(paper.instructions)}</p></section>}
  {sections.map(section=><section key={section.id} className="rm-card" style={{padding:20,marginTop:16}}><div style={{borderBottom:"1px solid #e4e7ec",paddingBottom:12}}><span className="rm-label">Section</span><h2 style={{margin:"4px 0"}}>{section.title}</h2>{section.instructions&&<p style={{color:"#667085"}}>{section.instructions}</p>}{section.questions_to_attempt&&<strong>Attempt any {section.questions_to_attempt} questions.</strong>}</div>{items.filter(item=>item.section_id===section.id).map((item,index)=>{const q=item.question_snapshot;const options=(q.options||[]) as Array<Record<string,unknown>>;return <article key={item.id} style={{padding:"20px 0",borderBottom:"1px solid #eef1f5"}}><div style={{display:"flex",justifyContent:"space-between",gap:10}}><strong>Q{index+1}. {String(q.stem_text||"")}</strong><span>{item.marks} / −{item.negative_marks}</span></div>{Boolean(q.stem_latex)&&<div style={{overflowX:"auto",marginTop:8}}><BlockMath math={String(q.stem_latex)}/></div>}{Boolean(q.question_image_url)&&<img src={String(q.question_image_url)} alt="Question" style={{maxWidth:"100%",maxHeight:320,objectFit:"contain",marginTop:10,borderRadius:10}}/>}<div style={{display:"grid",gap:8,marginTop:12}}>{options.map(option=><div key={String(option.option_key)} style={{padding:11,borderRadius:10,border:option.is_correct?"2px solid #137a3a":"1px solid #e4e7ec",background:option.is_correct?"#ecfdf3":"white"}}><strong>{String(option.option_key)}.</strong> {String(option.content_text||"")}{Boolean(option.content_latex)&&<InlineMath math={String(option.content_latex)}/>} {Boolean(option.is_correct)&&<span style={{color:"#137a3a",fontWeight:800}}>✓ Correct</span>}{Boolean(option.image_url)&&<img src={String(option.image_url)} alt="Option" style={{display:"block",maxWidth:220,maxHeight:130,objectFit:"contain",marginTop:7}}/>}</div>)}</div>{Boolean(q.solution_text)&&<div style={{marginTop:12,padding:12,background:"#f8fafc",borderRadius:10}}><strong>Solution:</strong> {String(q.solution_text)}</div>}</article>})}</section>)}
  </div>;
}
