"use client";
import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {Archive,CalendarClock,ClipboardCheck,Eye,FilePlus2,GitCompareArrows,LoaderCircle,Pencil,PlayCircle} from "lucide-react";
import {supabase} from "@/lib/supabase";
import type {PaperListRow,PaperStatus} from "@/types/papers";
import {useQuestionScope} from "@/components/questions/useQuestionScope";
import {SortableDataTable,type DataColumn} from "@/components/ui/SortableDataTable";
import {MetricInfo} from "@/components/ui/MetricInfo";
import {metricDefinitions} from "@/lib/evidaraMetrics";
const now=new Date().toISOString();
const demo:PaperListRow[]=[{id:"demo-paper",organization_id:null,title:"NEET Full Syllabus Mock 01",code:"NEET-M01",description:"Shared benchmark paper",exam_type:"NEET",status:"published",duration_minutes:180,total_marks:720,total_questions:180,access_mode:"public",available_from:null,available_until:null,attempt_limit:1,result_mode:"score_only",created_at:now,updated_at:now}];
export function QuestionPaperList({kind}:{kind:"admin"|"school"}){
 const{organizationId,organizationName,loading:scopeLoading,error:scopeError}=useQuestionScope(kind);const[papers,setPapers]=useState<PaperListRow[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("");const base=kind==="admin"?"/admin/papers":"/school/papers";
 async function load(){if(!supabase){setPapers(demo);setLoading(false);return}if(kind==="school"&&scopeLoading)return;setLoading(true);let q=supabase.from("question_papers").select("id,organization_id,title,code,description,exam_type,status,duration_minutes,total_marks,total_questions,access_mode,available_from,available_until,attempt_limit,result_mode,created_at,updated_at").order("updated_at",{ascending:false});q=kind==="admin"?q.is("organization_id",null):q.eq("organization_id",organizationId!);const{data,error:e}=await q;if(e)setError(e.message);else setPapers((data||[])as PaperListRow[]);setLoading(false)}
 useEffect(()=>{void load()},[kind,organizationId,scopeLoading]);
 async function setStatus(id:string,status:PaperStatus){if(!supabase)return;const{error:e}=await supabase.rpc("set_question_paper_status",{p_paper_id:id,p_status:status});if(e)setError(e.message);else await load()}
 const columns=useMemo<DataColumn<PaperListRow>[]>(()=>[
  {key:"title",label:"Paper",value:p=>p.title,render:p=><><strong>{p.title}</strong><small>{p.code||"No paper code"}</small></>},{key:"exam",label:"Exam",value:p=>p.exam_type,filter:{label:"exam types",value:p=>p.exam_type}},{key:"questions",label:"Questions",value:p=>p.total_questions,align:"right"},{key:"marks",label:"Marks",value:p=>p.total_marks,align:"right"},{key:"duration",label:"Duration",value:p=>p.duration_minutes,render:p=>`${p.duration_minutes} min`,align:"right"},{key:"access",label:"Access",value:p=>p.access_mode,filter:{label:"access modes",value:p=>p.access_mode}},{key:"status",label:"Status",value:p=>p.status,render:p=><span className={`so-status ${p.status==="published"?"success":"neutral"}`}>{p.status}</span>,filter:{label:"statuses",value:p=>p.status}},
  {key:"benchmark",label:<span className="ev-metric-label">Benchmark<MetricInfo {...metricDefinitions.benchmark}/></span>,value:p=>p.status==="published",render:p=>kind==="school"&&p.status==="published"?<Link href="/school/benchmarks/" className="ev-segment-pill"><GitCompareArrows/>Configure</Link>:<span style={{color:"#AEB8BC"}}>Unavailable</span>},
  {key:"actions",label:"Actions",value:p=>p.updated_at,sortable:false,render:p=><div className="so-action-row"><Link href={`${base}/preview/?id=${p.id}`} className="rm-btn-secondary" title="Preview"><Eye/></Link>{!p.id.startsWith("demo")&&<><Link href={`${base}/new/?id=${p.id}`} className="rm-btn-secondary" title="Edit"><Pencil/></Link>{p.status!=="published"?<button className="rm-btn-secondary" onClick={()=>void setStatus(p.id,"published")}><PlayCircle/></button>:<button className="rm-btn-secondary" onClick={()=>void setStatus(p.id,"archived")}><Archive/></button>}</>}</div>},
 ],[base,kind]);
 const stats={total:papers.length,published:papers.filter(p=>p.status==="published").length,drafts:papers.filter(p=>p.status==="draft").length,questions:papers.reduce((n,p)=>n+p.total_questions,0)};
 return <div><div className="so-page-head"><div><span className="so-kicker">{organizationName} · EVIDARA ASSESSMENTS</span><h1>Tests and question papers</h1><p>Sort every column and configure a published school paper as a persisted anonymous benchmark.</p></div><Link className="so-btn so-btn-primary" href={`${base}/new/`}><FilePlus2/>Create question paper</Link></div>{(scopeError||error)&&<div className="so-notice warning">{scopeError||error}</div>}<section className="paper-stats" style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:12}}>{Object.entries(stats).map(([label,value])=><div className="so-card so-pad" key={label}><strong style={{fontSize:28}}>{value}</strong><div>{label}</div></div>)}</section><section className="so-card so-pad so-mt">{loading?<div className="ev-empty-benchmark"><LoaderCircle className="spin"/>Loading papers…</div>:papers.length?<SortableDataTable rows={papers} columns={columns} rowKey={p=>p.id} searchText={p=>`${p.title} ${p.code} ${p.exam_type} ${p.status}`} searchPlaceholder="Search paper, code, exam or status"/>:<div className="ev-empty-benchmark"><ClipboardCheck/><h3>No question papers yet</h3></div>}</section><div style={{marginTop:13,color:"#6B7980",fontSize:12}}><CalendarClock/>A paper becomes shared only after it is configured on the Shared Benchmarks page.</div></div>;
}
