"use client";
import { useEffect, useState } from "react";
import { BarChart3, CheckCircle2, Clock3, LoaderCircle, XCircle } from "lucide-react";
import { supabase } from "@/lib/supabase";
import type { AttemptResult } from "@/types/papers";

export function StudentResults(){
  const [rows,setRows]=useState<AttemptResult[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");
  useEffect(()=>{load()},[]);
  async function load(){if(!supabase){setLoading(false);return;}const {data,error}=await supabase.rpc("list_my_attempt_results");if(error)setError(error.message);else setRows((data||[]) as AttemptResult[]);setLoading(false)}
  return <div><div><span className="rm-label">Performance history</span><h1 style={{margin:"5px 0",fontSize:34,color:"#131e35"}}>My test results</h1><p style={{margin:0,color:"#667085"}}>Every submitted paper is stored for progress comparison in the analytics version.</p></div>{error&&<div style={{marginTop:14,padding:12,background:"#fef3f2",color:"#b42318",borderRadius:12}}>{error}</div>}{loading?<div style={{padding:45,textAlign:"center",color:"#667085"}}><LoaderCircle className="spin"/> Loading results…</div>:rows.length===0?<div className="rm-card" style={{padding:45,textAlign:"center",marginTop:18}}><BarChart3 size={32} color="#98a2b3"/><h3>No submitted tests yet</h3><p style={{color:"#667085"}}>Complete a published question paper to create your first result.</p></div>:<div style={{display:"grid",gap:13,marginTop:18}}>{rows.map(row=><article key={row.attempt_id} className="rm-card" style={{padding:18}}><div style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"start",flexWrap:"wrap"}}><div><span className="rm-label">{row.status}</span><h3 style={{margin:"5px 0",color:"#131e35"}}>{row.paper_title}</h3><div style={{fontSize:12,color:"#667085"}}><Clock3 size={14}/> {new Date(row.started_at).toLocaleString()}</div></div><div style={{textAlign:"right"}}><strong style={{fontSize:28,color:row.percentage>=50?"#137a3a":"#b42318"}}>{row.score}/{row.maximum_marks}</strong><div style={{fontSize:13,color:"#667085"}}>{row.percentage}%</div></div></div><div className="result-grid" style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:9,marginTop:14}}><div style={{padding:11,background:"#ecfdf3",borderRadius:10,color:"#137a3a"}}><CheckCircle2 size={16}/> <strong>{row.correct_count}</strong> Correct</div><div style={{padding:11,background:"#fef3f2",borderRadius:10,color:"#b42318"}}><XCircle size={16}/> <strong>{row.incorrect_count}</strong> Incorrect</div><div style={{padding:11,background:"#f2f4f7",borderRadius:10,color:"#667085"}}><strong>{row.unanswered_count}</strong> Unanswered</div></div></article>)}</div>}<style>{`@media(max-width:560px){.result-grid{grid-template-columns:1fr!important}}`}</style></div>
}
