"use client";
import { useState } from "react";
import { Building2, CheckCircle2 } from "lucide-react";
import { supabase } from "@/lib/supabase";

export function SchoolRegistrationForm(){const [form,setForm]=useState({name:"",type:"Coaching School",city:"",state:"Karnataka",phone:"",student_count:"1-100"});const [done,setDone]=useState(false);const [message,setMessage]=useState("");
 const change=(k:string,v:string)=>setForm(p=>({...p,[k]:v}));
 async function submit(e:React.FormEvent){e.preventDefault();setMessage("");if(!supabase){localStorage.setItem("scholaros_demo_school",JSON.stringify(form));setDone(true);return;}const {data:{user}}=await supabase.auth.getUser();if(!user){setMessage("Please login first, then return to this form.");return;}const {error}=await supabase.rpc("create_school",{p_name:form.name,p_type:form.type,p_city:form.city,p_state:form.state,p_phone:form.phone,p_student_count:form.student_count});if(error){setMessage(error.message);return;}setDone(true)}
 if(done)return <div className="rm-card" style={{padding:30,textAlign:"center",maxWidth:620,margin:"0 auto"}}><CheckCircle2 size={54} color="#137a3a" style={{margin:"0 auto 14px"}}/><h2>School workspace created</h2><p style={{color:"#667085"}}>Your school details were saved. Open the school dashboard to continue.</p><a href="/school/" className="rm-btn-primary" style={{display:"inline-block",marginTop:12}}>Open School Dashboard</a></div>;
 return <form onSubmit={submit} className="rm-card" style={{padding:24,maxWidth:720,margin:"0 auto"}}><div style={{display:"flex",gap:12,alignItems:"center",marginBottom:20}}><span style={{background:"#fff4cc",padding:11,borderRadius:12}}><Building2 color="#8a5f00"/></span><div><h2 style={{margin:0}}>Register your school</h2><p style={{margin:"4px 0 0",color:"#667085"}}>Create the school workspace first, then activate an annual school plan from the live store.</p></div></div>
 <div className="rm-grid" style={{gridTemplateColumns:"repeat(2,minmax(0,1fr))"}}><label style={{gridColumn:"1/-1"}}><span className="rm-label">School name</span><input className="rm-input" value={form.name} onChange={e=>change("name",e.target.value)} required/></label><label><span className="rm-label">School type</span><select className="rm-input" value={form.type} onChange={e=>change("type",e.target.value)}><option>Coaching School</option><option>School</option><option>College</option><option>Independent Educator</option></select></label><label><span className="rm-label">Approx. students</span><select className="rm-input" value={form.student_count} onChange={e=>change("student_count",e.target.value)}><option>1-100</option><option>101-500</option><option>501-2000</option><option>2000+</option></select></label><label><span className="rm-label">City</span><input className="rm-input" value={form.city} onChange={e=>change("city",e.target.value)} required/></label><label><span className="rm-label">State</span><input className="rm-input" value={form.state} onChange={e=>change("state",e.target.value)} required/></label><label style={{gridColumn:"1/-1"}}><span className="rm-label">Phone number</span><input className="rm-input" value={form.phone} onChange={e=>change("phone",e.target.value)} required/></label></div><button className="rm-btn-primary" style={{marginTop:20,width:"100%"}}>Create School Workspace</button>{message&&<p style={{color:"#b42318"}}>{message}</p>}<style jsx>{`@media(max-width:640px){.rm-grid{grid-template-columns:1fr!important}}`}</style></form>}
