from pathlib import Path

checklist = Path('PHASE1_RELEASE_CHECKLIST.md')
text = checklist.read_text()
old = '- [ ] F2 Define metric dictionary: Tests Taken, Unique Questions, Question Outcomes, Attempted, Unanswered, Accuracy, Score %, Participation.'
new = '- [x] **F2 Canonical analytics metric dictionary** — verified 1 Sep 2026. `src/lib/evidaraMetrics.ts` now defines one shared product contract for Tests Taken, Unique Questions, Question Outcomes, Attempted, Unanswered, Accuracy, Score % and Participation, including numerator/denominator rules and explicit `Not assessed` empty semantics. The dictionary distinguishes repeated question outcomes from distinct canonical questions, defines Accuracy as correct/attempted, Score % as pooled marks awarded / marks available rather than an unweighted average of test percentages, and Participation from frozen eligible assignment opportunities rather than question attempt rate. Permanent `f2-analytics-metric-dictionary-smoke.mjs` checks the dictionary against the evidence SQL. Exact candidate `f1a2cb2375a8e9f52ae81f4bd7eb8e99752f96d8` passed complete release gate `33483020214` (1m54s), including TypeScript, lint, every regression and production build.'
if old not in text:
    raise SystemExit('F2 unchecked checklist line not found')
checklist.write_text(text.replace(old, new, 1))

log = Path('PHASE1_PROGRESS_LOG.md')
entry = '''\n\n## 2026-09-01 12:58:26 IST — F2 canonical analytics metric dictionary (verified) / hourly heartbeat\n\n- **Run start/end:** 2026-09-01 12:58:26 IST → approximately 13:13 IST.\n- **Section worked:** F — Results and analytics.\n- **Checklist items completed:** F2. F3–F13 remain pending.\n- **Starting branch head:** `b655029608a8fc2383e14314b2fa06f45c8649b2`.\n- **Implementation result:** Centralized the eight Phase-1 analytics metric contracts in `src/lib/evidaraMetrics.ts`: submitted-attempt Tests Taken; distinct canonical Unique Questions; repeated Question Outcomes; Attempted = correct + incorrect; Unanswered = outcomes − attempted; Accuracy = correct / attempted with no-denominator `Not assessed`; pooled Score % = marks awarded / marks available; and assignment-based Participation from frozen/materialized eligible opportunities.\n- **Commits created:** F2 dictionary, permanent smoke, release-gate wiring and rework candidate `f1a2cb2375a8e9f52ae81f4bd7eb8e99752f96d8`, followed by documentation-recorder cleanup commits.\n- **CI:** Initial gate `33482884639` failed only the new empty-state assertion because it counted the TypeScript type declaration as a ninth occurrence. The assertion was scoped to the canonical dictionary block. Exact candidate `f1a2cb2375a8e9f52ae81f4bd7eb8e99752f96d8` then passed complete release gate `33483020214`, 13:07:29–13:09:23 IST, **1m54s — PASS**, including F2, TypeScript, lint, all regressions and production build.\n- **Vercel/Supabase state:** Vercel production showed no runtime errors in the preceding 24 hours. Both connected Supabase projects reported `ACTIVE_HEALTHY`; F2 required no database mutation. Permanent production remained protected and unpromoted.\n- **Rework/failures/blockers:** One F2 test-only false negative was corrected. A first temporary recorder workflow was rejected before jobs ran; it made no product/production change and was removed. F3 inspection confirmed the top-level zero-test state is already explicit, but deeper percentage/rate render paths still require denominator-aware `Not assessed` semantics. No user-input blocker exists.\n- **Active engineering/review span:** approximately **15 minutes** in the available execution window. The 45–50 minute target was **not met because the tool execution window ended earlier**; no artificial padding was added.\n- **Section progress:** F is **2/13 verified = 15.4%**.\n- **Overall Phase 1 progress:** **60/129 verified = 46.5%**.\n- **Exact next action:** F3 — audit every student/institution analytics percentage/rate display, distinguish genuine measured zero from absent denominator, centralize `Not assessed`/`—` display semantics, add permanent F3 regression and require an exact full-gate PASS before checking F3.\n'''
log.write_text(log.read_text() + entry)
Path('.github/workflows/f2-recorder.yml').unlink(missing_ok=True)
Path('scripts/f2-recorder.py').unlink(missing_ok=True)
