import fs from 'node:fs';
const read=(p)=>fs.readFileSync(p,'utf8'); let n=0;
function ok(name,cond){if(!cond)throw new Error(`V14 smoke failed: ${name}`);console.log(`PASS ${++n}: ${name}`)}
const pkg=JSON.parse(read('package.json'));
const release=read('src/lib/release.ts');
const sidebar=read('src/components/evidara/app-sidebar.tsx');
const page=read('src/app/page.tsx');
const access=read('src/app/api/access-control/route.ts');
const questions=read('src/components/evidara/live-question-bank.tsx');
const papers=read('src/components/evidara/live-paper-catalogue-v8.tsx');
const resources=read('src/components/evidara/resource-manager-v14.tsx');
const resourceApi=read('src/app/api/resources-v14/route.ts');
const self=read('src/components/evidara/self-assessment-center.tsx');
const referral=read('src/components/commerce/ReferralCenter.tsx');
const admin=read('src/components/evidara/admin-v14-views.tsx');
const overview=read('src/app/api/admin/platform-overview/route.ts');
const lifecycle=read('src/components/school/StudentLifecycleManager.tsx');
ok('current package release is V19',pkg.version==='19.1.0');
ok('release metadata is V19',release.includes("19.1.0")&&release.includes('Evidara V19'));
ok('student sidebar exposes Results',sidebar.includes("view: 'student-results'"));
ok('student sidebar exposes Self Assessment',sidebar.includes("view: 'student-self-assessment'"));
ok('student sidebar contains Refer & Earn',sidebar.includes('Refer & Earn'));
ok('school-enrolled students are excluded from public referral promotion',referral.includes('student_school_memberships'));
ok('teacher question label is My Questions',sidebar.includes('My Questions'));
ok('teacher dashboard is live scoped',read('src/components/evidara/school-views.tsx').includes('Teacher Dashboard'));
ok('school student lifecycle exposes bulk CSV mapper',lifecycle.includes('BulkAccountImport'));
ok('bulk account API uses V14 scoped account creation',access.includes('bulkCreateAccounts')&&access.includes('assign_account_role_service_v14'));
ok('account directory uses server-safe V14 RPC',access.includes('admin_account_directory_service_v14'));
ok('question bank implements teacher own-question scope',questions.includes('p_only_mine')&&questions.includes("role === 'school_teacher'"));
ok('Evidara Admin does not publish platform questions directly',questions.includes('canPublish'));
ok('paper catalogue has Super Admin publication governance',papers.includes('canApprove'));
ok('hierarchical resource manager exists',resources.includes('New folder')&&resources.includes('Upload file'));
ok('resource API uploads to R2',resourceApi.includes('uploadResourceFileToR2'));
ok('student/school resource hierarchy is shared',read('src/components/school/ResourceLibrary.tsx').includes('ResourceManagerV14'));
ok('super admin resource inventory exists',admin.includes('AdminResourcesView'));
ok('institutions module exists',admin.includes('AdminInstitutionsView'));
ok('referral settings view exists',admin.includes('ReferralSettingsView'));
ok('self assessment center uses V14 wallet',self.includes('ensure_self_assessment_wallet_v14'));
ok('self assessment generation uses V14 server RPC',self.includes('generate_self_assessment_test_v14'));
ok('self assessment supports multi-select scopes without exposing exam distribution',self.includes('Choose one, several, or all')&&!self.includes('Physics 45 · Chemistry 45'));
ok('self assessment uses focused UI caps',self.includes("testType === 'topic'")&&self.includes("testType === 'chapter'")&&self.includes("testType === 'subject'"));
ok('platform aggregate revenue is Super Admin only',overview.includes('isSuperAdmin'));
ok('V14 routes are connected in root workspace',page.includes('AdminInstitutionsView')&&page.includes('SelfAssessmentCenter'));
console.log(`V14 smoke passed (${n}/${n}).`);
