import Link from "next/link";
import { Award, BarChart3, BookOpenCheck, CircleHelp, ClipboardCheck, Clock3, Sparkles, Target, TrendingUp } from "lucide-react";
import { ProtectedPage } from "@/components/ProtectedPage";
import { DashboardShell } from "@/components/DashboardShell";
import { MetricInfo, MetricLabel } from "@/components/ui/MetricInfo";
import { metricDefinitions, segmentDefinitions } from "@/lib/evidaraMetrics";

export default function StudentDashboard(){const segment=segmentDefinitions.high_potential_careless;return <ProtectedPage allowed="student"><DashboardShell kind="student"><div className="so-page-head"><div><span className="so-kicker">YOUR DEVELOPMENT PLAN</span><h1>Good morning, Ananya</h1><p>Your next task is selected from your actual response patterns, not from a generic homework list.</p><Link href="/metric-guide/" className="ev-guide-link"><CircleHelp size={16}/>Understand my metrics and segment</Link></div><Link href="/student/tests/" className="so-btn so-btn-primary">Take an assessment</Link></div>
<section className="analytics-command"><div><span className="so-kicker light">CURRENT DEVELOPMENT SEGMENT</span><div className="ev-dark-metric-title"><h2>{segment.label}</h2><MetricInfo {...metricDefinitions.segment}/></div><p>{segment.rule}</p><div className="so-inline-stats"><div><strong>84%</strong><span><MetricLabel {...metricDefinitions.accuracy}>latest accuracy</MetricLabel></span></div><div><strong>91st</strong><span><MetricLabel {...metricDefinitions.percentile}>percentile</MetricLabel></span></div><div><strong>+26</strong><span><MetricLabel {...metricDefinitions.trend}>score gain</MetricLabel></span></div></div></div><div className="readiness-ring"><strong>82</strong><span><MetricLabel {...metricDefinitions.readiness}>readiness index</MetricLabel></span></div></section>
<div className="so-grid so-grid-4 so-mt"><div className="so-stat"><Award/><strong>584</strong><span><MetricLabel {...metricDefinitions.score}>Latest score</MetricLabel></span></div><div className="so-stat"><TrendingUp/><strong>+26</strong><span><MetricLabel {...metricDefinitions.trend}>Since first test</MetricLabel></span></div><div className="so-stat"><Clock3/><strong>68 sec</strong><span><MetricLabel {...metricDefinitions.averageQuestionTime}>Average question time</MetricLabel></span></div><div className="so-stat"><Target/><strong>650</strong><span><MetricLabel {...metricDefinitions.target}>Current target</MetricLabel></span></div></div>
<div className="so-grid so-grid-3 so-mt"><Link href="/student/tests/" className="so-card so-pad benefit-card"><span className="so-label free">FREE</span><ClipboardCheck/><h3>School tests</h3><p>Take tests created by your school within its annual Evidara plan.</p></Link><Link href="/student/resources/" className="so-card so-pad benefit-card"><span className="so-label complimentary">COMPLIMENTARY</span><BookOpenCheck/><h3>Eligible previous papers</h3><p>Access board, NEET, JEE or KCET resources assigned for your grade and preparation track.</p></Link><Link href="/student/analytics/" className="so-card so-pad benefit-card"><span className="so-label included">INTELLIGENCE</span><BarChart3/><h3>Detailed analytics</h3><p>See topic mastery, error causes, speed, improvement and your teacher-ready next plan.</p></Link></div>
<div className="so-grid so-grid-2 so-mt"><section className="so-card so-pad"><div className="so-section-head"><div><span className="so-kicker">NEXT THREE ACTIONS</span><h2>Your priority plan</h2></div><Target/></div><div className="so-steps"><div><b>1</b><span><strong>Ratio & Proportion</strong><small>12 controlled questions without a timer.</small></span></div><div><b>2</b><span><strong>Kinematics speed set</strong><small>15 questions with a 75-second cap.</small></span></div><div><b>3</b><span><strong>Seven-day retest</strong><small>Target 80% accuracy with no more than two avoidable errors.</small></span></div></div></section><section className="so-card so-pad"><div className="so-section-head"><div><span className="so-kicker">WHY THIS SEGMENT APPEARS</span><h2>{segment.label}</h2></div><MetricInfo {...metricDefinitions.segment}/></div><div className="ev-segment-definition"><span>Current rule</span><p>{segment.rule}</p><span>Recommended next action</span><p>{segment.nextAction}</p><span>Recalculation</span><p>After every valid comparable assessment. This can change as new evidence is collected.</p></div></section></div>
<div className="so-card so-pad so-mt"><div className="so-section-head"><div><span className="so-kicker">RESOURCE ELIGIBILITY</span><h2>Grade 10 · State Board · NEET</h2></div><Sparkles/></div><p style={{color:"#6B7980",lineHeight:1.6}}>You can access Grade 10 Karnataka board papers, Foundation resources and your assigned early-NEET preparation material. Grade 12 and KCET papers remain locked until eligible.</p><Link href="/student/resources/" className="rm-btn-secondary">Open my resources</Link></div>
</DashboardShell></ProtectedPage>}
