import Link from "next/link";
import { BookOpenCheck, ClipboardCheck, CreditCard, FileQuestion, GraduationCap, ShieldCheck, Sparkles, Upload, Users } from "lucide-react";
import { ProtectedPage } from "@/components/ProtectedPage";import { DashboardShell } from "@/components/DashboardShell";
export default function SchoolDashboard(){return <ProtectedPage allowed="school"><DashboardShell kind="school"><div className="so-page-head"><div><span className="so-kicker">SCHOOL LEARNING OPERATIONS</span><h1>Green Valley School</h1><p>Build tests, manage the annual roster, control eligibility and turn student responses into teacher actions.</p></div><div className="so-action-row"><Link href="/school/questions/import/" className="rm-btn-secondary"><Upload size={17}/>Import questions</Link><Link href="/school/papers/new/" className="so-btn so-btn-primary">Create free test</Link></div></div>
<section className="so-hero-card subscription-hero"><div><span className="so-kicker light">ANNUAL ACCESS ACTIVE</span><h2>Valid through 31 May 2027</h2><p>342 active students from a 500-seat plan. School-created tests have no per-test charge; eligible PYQs are complimentary.</p><div className="so-inline-stats"><div><strong>342</strong><span>active students</span></div><div><strong>18</strong><span>published tests</span></div><div><strong>83%</strong><span>assessment participation</span></div><div><strong>5</strong><span>teacher interventions</span></div></div></div><Link href="/school/subscription/" className="so-btn so-btn-accent"><CreditCard size={17}/>Manage subscription</Link></section>
<div className="so-grid so-grid-4 so-mt"><Link href="/school/students/" className="so-stat"><Users/><strong>Roster</strong><span>Promote or revoke students</span></Link><Link href="/school/papers/" className="so-stat"><ClipboardCheck/><strong>FREE</strong><span>School-created tests</span></Link><Link href="/school/resources/" className="so-stat"><BookOpenCheck/><strong>PYQs</strong><span>Complimentary resources</span></Link><Link href="/school/questions/" className="so-stat"><FileQuestion/><strong>Bank</strong><span>Private and licensed questions</span></Link></div>
<div className="so-grid so-grid-2 so-mt"><section className="so-card so-pad"><div className="so-section-head"><div><span className="so-kicker">NEXT OPERATING ACTIONS</span><h2>Before the next academic year</h2></div><GraduationCap/></div><div className="so-steps"><div><b>1</b><span><strong>Review students who left</strong><small>Revoke them before bulk promotion so they remain permanently excluded.</small></span></div><div><b>2</b><span><strong>Promote the eligible roster</strong><small>Promote one student or all active, unlocked students to 2027–28.</small></span></div><div><b>3</b><span><strong>Renew school access</strong><small>Continue publishing tests and using complimentary resources beyond May 2027.</small></span></div></div><Link href="/school/students/" className="so-btn so-btn-primary" style={{marginTop:14}}>Open student lifecycle</Link></section>
<section className="so-card so-pad"><div className="so-section-head"><div><span className="so-kicker">RESOURCE GOVERNANCE</span><h2>Eligibility is student-specific</h2></div><ShieldCheck/></div><div className="so-check-list"><li><Sparkles/> State Board Grade 10 students receive SSLC previous papers.</li><li><Sparkles/> Grade 12 State Board students receive 2nd PUC resources.</li><li><Sparkles/> NEET, JEE and KCET require Grades 11–12 and an assigned track.</li><li><Sparkles/> Olympiad and Foundation resources target Grades 8–10.</li></div><Link href="/school/resources/" className="rm-btn-secondary" style={{marginTop:14}}>Preview student eligibility</Link></section></div>
<div className="so-grid so-grid-3 so-mt"><article className="so-card so-pad insight-card"><FileQuestion/><span className="so-kicker">QUESTION PIPELINE</span><h3>Manual, Excel, CSV and ZIP</h3><p>Create equations, images and solutions or bulk-import them into the private school bank.</p></article><article className="so-card so-pad insight-card"><ClipboardCheck/><span className="so-kicker">PAPER BUILDER</span><h3>Auto, hybrid or manual</h3><p>Use sections, difficulty mix, schedules, access codes, negative marks and attempt controls.</p></article><article className="so-card so-pad insight-card"><GraduationCap/><span className="so-kicker">TEACHER INTELLIGENCE</span><h3>From error to intervention</h3><p>Group students by the misconception they share, then schedule practice and a retest.</p></article></div>
</DashboardShell></ProtectedPage>}
